
CREATE (GTM:Pais {Nombre: 'Guatemala'})
CREATE (rpeten:Region {Nombre: 'Petén'})
CREATE (metropolitana:Region {Nombre: 'Metropolitana'})
CREATE (norte:Region {Nombre: 'Norte'})
CREATE (nororiente:Region {Nombre: 'Nororiente'})
CREATE (suroriente:Region {Nombre: 'Suroriente'})
CREATE (central:Region {Nombre: 'Central'})
CREATE (suroccidente:Region {Nombre: 'Suroccidente'})
CREATE (noroccidente:Region {Nombre: 'Noroccidente'})
CREATE (peten:Municipio {titulo: 'Petén'})
CREATE (cguatemala:Municipio {titulo: 'Ciudad de Guatemala'})
CREATE (altaVerapaz:Municipio {titulo: 'Alta Verapaz'})
CREATE (bajaVerapaz:Municipio {titulo: 'Baja Verapaz'})
CREATE (chiquimula:Municipio {titulo: 'Chiquimula'})
CREATE (elProgreso:Municipio {titulo: 'El Progreso'})
CREATE (izabal:Municipio {titulo: 'Izabal'})
CREATE (Zacapa:Municipio {titulo: 'Zacapa'})
CREATE (jalapa:Municipio {titulo: 'Jalapa'})
CREATE (jutiapa:Municipio {titulo: 'Jutiapa'})
CREATE (santaRosa:Municipio {titulo: 'Santa Rosa'})
CREATE (chimaltenango:Municipio {titulo: 'Chimaltenango'})
CREATE (escuintla:Municipio {titulo: 'Escuintla'})
CREATE (sacatepequez:Municipio {titulo: 'Sacatepéquez'})
CREATE (retalhuleu:Municipio {titulo: 'Retalhuleu'})
CREATE (sanMarcos:Municipio {titulo: 'San Marcos'})
CREATE (solola:Municipio {titulo: 'Sololá'})
CREATE (suchitepequez:Municipio {titulo: 'Suchitepéquez'})
CREATE (totonicapan:Municipio {titulo: 'Totonicapán'})
CREATE (quetzaltenango:Municipio {titulo: 'Quetzaltenango'})
CREATE (Huehue:Municipio {titulo: 'Huehuetenango'})
CREATE (frio:Clima {titulo: 'Frío'})
CREATE (calido:Clima {titulo: 'Cálido'})
CREATE (templado:Clima {titulo: 'Templado'})
CREATE (lluvioso:Clima {titulo: 'Lluvioso'})
CREATE (humedo:Clima {titulo: 'Húmedo'})
CREATE (gt_museoPopolVuh:Turismo {Lugar: 'Museo Popol Vuh'})
CREATE (pet_tikal:Turismo {Lugar: 'Tikal'})
CREATE (pet_islaFlores:Turismo {Lugar: 'Isla de Flores'})
CREATE (pet_resBiosferaMaya:Turismo {Lugar: 'Reserva de la Biosfera Maya'})
CREATE (pet_lagunaYaxha:Turismo {Lugar: 'Laguna Yaxhá'})
CREATE (pet_pNacLagunaTigre:Turismo {Lugar: 'Parque Nacional Laguna del Tigre'})
CREATE (pet_pNacSierraLacandon:Turismo {Lugar: 'Parque Nacional Sierra del Lacandón'})
CREATE (pet_lagunaPetexbatun:Turismo {Lugar: 'Laguna Petexbatún'})
CREATE (pet_petencito:Turismo {Lugar: 'Petencito'})
CREATE (pet_parqueActunKan:Turismo {Lugar: 'Parque Regional Actún Kan'})
CREATE (pet_craterAzul:Turismo {Lugar: 'Cráter Azul'})
CREATE (gt_museoArqueologia:Turismo {Lugar: 'Museo Nacional de Arqueología y Etnología de Guatemala'})
CREATE (gt_mapaRelieve:Turismo {Lugar: 'Mapa en Relieve de Guatemala'})
CREATE (gt_mercadoCentral:Turismo {Lugar: 'Mercado Central'})
CREATE (gt_museoFerrocarril:Turismo {Lugar: 'Museo del Ferrocarril de Guatemala'})
CREATE (gt_museoIxchel:Turismo {Lugar: 'Museo Ixchel del Traje Indígena'})
CREATE (gt_museoNacionalArte:Turismo {Lugar: 'Museo Nacional de Arte Moderno Carlos Mérida'})
CREATE (gt_iglesiaCerritoCarmen:Turismo {Lugar: 'Iglesia del Cerrito del Carmen'})
CREATE (gt_hipodromoNorte:Turismo {Lugar: 'Hipódromo del Norte'})
CREATE (gt_kaminaljuyu:Turismo {Lugar: 'Zona Arqueológica Kaminaljuyu'})
CREATE (gt_jardinBotanico:Turismo {Lugar: 'Jardín Botánico de Guatemala'})
CREATE (gt_museoHolocausto:Turismo {Lugar: 'Museo del Holocausto Guatemala'})
CREATE (jut_lagoGuija:Turismo {Lugar: 'Lago de Guija'})
CREATE (jut_lagunaAtescatempa:Turismo {Lugar: 'Laguna Atescatempa'})
CREATE (jut_playaMarina:Turismo {Lugar: 'Playas Marinas'})
CREATE (jut_volcanViboras:Turismo {Lugar: 'Volcán de las Víboras'})
CREATE (jut_volcanChingo:Turismo {Lugar: 'Volcán Chingo'})
CREATE (jut_volcanIxtepeque:Turismo {Lugar: 'Volcán Ixtepeque'})
CREATE (jut_volcanSuchitan:Turismo {Lugar: 'Volcán Suchitán'})
CREATE (jut_volcanMoyuta:Turismo {Lugar: 'Volcán Moyuta'})
CREATE (jut_cuevaAndaMira:Turismo {Lugar: 'Cueva de Anda Mirá'})
CREATE (jal_cascadaTatasirire:Turismo {Lugar: 'Cascadas de Tatasirire'})
CREATE (jal_lagunaAchiotes:Turismo {Lugar: 'Laguna de Achiotes Jumay'})
CREATE (jal_ruinasIngenioAyarza:Turismo {Lugar: 'Ruinas Coloniales del Ingenio Ayarza'})
CREATE (jal_iglesiaJilotepeque:Turismo {Lugar: 'Iglesia Colonial de San Luis Jilotepeque'})
CREATE (jal_lagunaHoyo:Turismo {Lugar: 'Laguna del Hoyo'})
CREATE (jal_volcanJumay:Turismo {Lugar: 'Volcán Jumay'})
CREATE (jal_volcanAlzatete:Turismo {Lugar: 'Volcán Alzatete'})
CREATE (chi_basilicaEsquipulas:Turismo {Lugar: 'Basílica de Esquipulas'})
CREATE (chi_cuevaMinas:Turismo {Lugar: 'La cueva de las Minas'})
CREATE (chi_fincaGirasoles:Turismo {Lugar: 'Finca Los Girasoles'})
CREATE (chi_volcanIpala:Turismo {Lugar: 'Volcán de Ipala'})
CREATE (chi_parqueMontecristo:Turismo {Lugar: 'Parque Nacional Montecristo o Trifinio'})
CREATE (zac_cerroMiramundos:Turismo {Lugar: 'Cerro Miramundo'})
CREATE (zac_museoFerrocarril:Turismo {Lugar: 'Museo del Ferrocarril Zacapa'})
CREATE (zac_ValleDorado:Turismo {Lugar: 'Turicentro Valle Dorado'})
CREATE (zac_museoPalenGeolo:Turismo {Lugar: 'Museo de Paleontología, Arqueología y Geología'})
CREATE (iz_arqueoQuirigua:Turismo {Lugar: 'Sitio Arqueológico de Quiriguá'})
CREATE (iz_castilloSanFelipe:Turismo {Lugar: 'Castillo de San Felipe de Lara'})
CREATE (iz_lagoIzabal:Turismo {Lugar: 'Lago de Izabal'})
CREATE (iz_playaDorada:Turismo {Lugar: 'Playa Dorada'})
CREATE (iz_rioDulce:Turismo {Lugar: 'Río Dulce'})
CREATE (iz_bahiaAmatique:Turismo {Lugar: 'Bahía de Amatique'})
CREATE (iz_puntaPalma:Turismo {Lugar: 'Punta de Palma'})
CREATE (iz_playaGraciosa:Turismo {Lugar: 'Playa La Graciosa'})
CREATE (iz_biotopoChacon:Turismo {Lugar: 'Biotopo Protegido Chacón Machacas'})
CREATE (iz_cayosDiablo:Turismo {Lugar: 'Los Cayos del Diablo'})
CREATE (pet_lagoItza:Turismo {Lugar: 'Lago Petén Itza'})
CREATE (gt_palacioNacional:Turismo {Lugar: 'Palacio Nacional de la Cultura'})
CREATE (gt_zooAurora:Turismo {Lugar: 'Zoológico La Aurora'})
CREATE (gt_catedralGuatemala:Turismo {Lugar: 'Catedral de Ciudad de Guatemala'})
CREATE (qeqchi:Idioma {titulo: 'Qeqchi'})
CREATE (pocomchi:Idioma {titulo: 'Pocomchi'})
CREATE (achi:Idioma {titulo: 'Achí'})
CREATE (kiche:Idioma {titulo: 'Kiche'})
CREATE (espaniol:Idioma {titulo: 'Español'})
CREATE (kaqchikel:Idioma {titulo: 'Kaqchikel'})
CREATE (pocoman:Idioma {titulo: 'Pocoman'})
CREATE (chorti:Idioma {titulo: 'Chortí'})
CREATE (garifuna:Idioma {titulo: 'Garífuna'})
CREATE (quekchi:Idioma {titulo: 'Quekchí'})
CREATE (mam:Idioma {titulo: 'Mam'})
CREATE (tzutujil:Idioma {titulo: 'Tzutujil'})
CREATE (ecoturismo:Tipo_Turismo {titulo: 'Ecoturismo'})
CREATE (comunitario:Tipo_Turismo {titulo: 'Comunitario'})
CREATE (cultural:Tipo_Turismo {titulo: 'Cultural'})
CREATE (gastronomico:Tipo_Turismo {titulo: 'Gastronómico'})
CREATE (agroturismo:Tipo_Turismo {titulo: 'Agroturismo'})
CREATE (aventura:Tipo_Turismo {titulo: 'Aventura'})
CREATE (deportivo:Tipo_Turismo {titulo: 'Deportivo'})
CREATE (etnoturismo:Tipo_Turismo {titulo: 'Etnoturismo'})
CREATE (religioso:Tipo_Turismo {titulo: 'Religioso'})
CREATE (arqueologico:Tipo_Turismo {titulo: 'Arqueológico'})


CREATE (rpeten)-[:REGION_PAIS {roles:['Region Pais']}]->(GTM)
CREATE (metropolitana)-[:REGION_PAIS {roles:['Region Pais']}]->(GTM)
CREATE (norte)-[:REGION_PAIS {roles:['Region Pais']}]->(GTM)
CREATE (nororiente)-[:REGION_PAIS {roles:['Region Pais']}]->(GTM)
CREATE (suroriente)-[:REGION_PAIS {roles:['Region Pais']}]->(GTM)
CREATE (central)-[:REGION_PAIS {roles:['Region Pais']}]->(GTM)
CREATE (suroccidente)-[:REGION_PAIS {roles:['Region Pais']}]->(GTM)
CREATE (noroccidente)-[:REGION_PAIS {roles:['Region Pais']}]->(GTM)
CREATE (peten)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(rpeten)
CREATE (cguatemala)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(metropolitana)
CREATE (altaVerapaz)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(norte)
CREATE (bajaVerapaz)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(norte)
CREATE (chiquimula)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(nororiente)
CREATE (elProgreso)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(nororiente)
CREATE (izabal)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(nororiente)
CREATE (Zacapa)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(nororiente)
CREATE (jalapa)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(suroriente)
CREATE (jutiapa)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(suroriente)
CREATE (santaRosa)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(suroriente)
CREATE (chimaltenango)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(central)
CREATE (escuintla)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(central)
CREATE (sacatepequez)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(central)
CREATE (retalhuleu)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(suroccidente)
CREATE (sanMarcos)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(suroccidente)
CREATE (solola)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(suroccidente)
CREATE (suchitepequez)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(suroccidente)
CREATE (totonicapan)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(suroccidente)
CREATE (quetzaltenango)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(suroccidente)
CREATE (Huehue)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(noroccidente)
CREATE (gt_museoPopolVuh)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(cguatemala)
CREATE (pet_tikal)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(peten)
CREATE (pet_islaFlores)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(peten)
CREATE (pet_resBiosferaMaya)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(peten)
CREATE (pet_lagunaYaxha)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(peten)
CREATE (pet_pNacLagunaTigre)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(peten)
CREATE (pet_pNacSierraLacandon)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(peten)
CREATE (pet_lagunaPetexbatun)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(peten)
CREATE (pet_petencito)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(peten)
CREATE (pet_parqueActunKan)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(peten)
CREATE (pet_craterAzul)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(peten)
CREATE (gt_museoArqueologia)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(cguatemala)
CREATE (gt_mapaRelieve)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(cguatemala)
CREATE (gt_mercadoCentral)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(cguatemala)
CREATE (gt_museoFerrocarril)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(cguatemala)
CREATE (gt_museoIxchel)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(cguatemala)
CREATE (gt_museoNacionalArte)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(cguatemala)
CREATE (gt_iglesiaCerritoCarmen)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(cguatemala)
CREATE (gt_hipodromoNorte)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(cguatemala)
CREATE (gt_kaminaljuyu)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(cguatemala)
CREATE (gt_jardinBotanico)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(cguatemala)
CREATE (gt_museoHolocausto)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(cguatemala)
CREATE (jut_lagoGuija)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jutiapa)
CREATE (jut_lagunaAtescatempa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jutiapa)
CREATE (jut_playaMarina)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jutiapa)
CREATE (jut_volcanViboras)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jutiapa)
CREATE (jut_volcanChingo)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jutiapa)
CREATE (jut_volcanIxtepeque)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jutiapa)
CREATE (jut_volcanSuchitan)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jutiapa)
CREATE (jut_volcanMoyuta)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jutiapa)
CREATE (jut_cuevaAndaMira)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jutiapa)
CREATE (jal_cascadaTatasirire)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jalapa)
CREATE (jal_lagunaAchiotes)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jalapa)
CREATE (jal_ruinasIngenioAyarza)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jalapa)
CREATE (jal_iglesiaJilotepeque)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jalapa)
CREATE (jal_lagunaHoyo)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jalapa)
CREATE (jal_volcanJumay)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jalapa)
CREATE (jal_volcanAlzatete)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jalapa)
CREATE (chi_basilicaEsquipulas)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(chiquimula)
CREATE (chi_cuevaMinas)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(chiquimula)
CREATE (chi_fincaGirasoles)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(chiquimula)
CREATE (chi_volcanIpala)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(chiquimula)
CREATE (chi_parqueMontecristo)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(chiquimula)
CREATE (zac_cerroMiramundos)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(Zacapa)
CREATE (zac_museoFerrocarril)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(Zacapa)
CREATE (zac_ValleDorado)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(Zacapa)
CREATE (zac_museoPalenGeolo)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(Zacapa)
CREATE (iz_arqueoQuirigua)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(izabal)
CREATE (iz_castilloSanFelipe)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(izabal)
CREATE (iz_lagoIzabal)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(izabal)
CREATE (iz_playaDorada)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(izabal)
CREATE (iz_rioDulce)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(izabal)
CREATE (iz_bahiaAmatique)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(izabal)
CREATE (iz_puntaPalma)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(izabal)
CREATE (iz_playaGraciosa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(izabal)
CREATE (iz_biotopoChacon)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(izabal)
CREATE (iz_cayosDiablo)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(izabal)
CREATE (pet_lagoItza)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(peten)
CREATE (gt_palacioNacional)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(cguatemala)
CREATE (gt_zooAurora)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(cguatemala)
CREATE (gt_catedralGuatemala)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(cguatemala)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(peten)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(cguatemala)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(altaVerapaz)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(bajaVerapaz)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(chiquimula)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(elProgreso)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(izabal)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(Zacapa)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(jalapa)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(jutiapa)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(santaRosa)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(chimaltenango)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(escuintla)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(sacatepequez)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(retalhuleu)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(sanMarcos)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(solola)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(suchitepequez)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(totonicapan)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(quetzaltenango)
CREATE (pocoman)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(jalapa)
CREATE (chorti)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(chiquimula)
CREATE (chorti)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(Zacapa)
CREATE (garifuna)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(izabal)
CREATE (quekchi)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(izabal)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pet_tikal)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pet_islaFlores)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pet_resBiosferaMaya)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pet_lagunaYaxha)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pet_pNacLagunaTigre)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pet_pNacSierraLacandon)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pet_lagunaPetexbatun)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pet_petencito)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pet_parqueActunKan)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pet_craterAzul)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jut_lagoGuija)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jut_lagunaAtescatempa)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jut_playaMarina)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jut_volcanViboras)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jut_volcanChingo)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jut_volcanIxtepeque)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jut_volcanSuchitan)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jut_volcanMoyuta)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jut_cuevaAndaMira)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jal_cascadaTatasirire)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jal_lagunaAchiotes)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jal_ruinasIngenioAyarza)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jal_iglesiaJilotepeque)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jal_lagunaHoyo)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jal_volcanJumay)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jal_volcanAlzatete)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(chi_basilicaEsquipulas)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(chi_cuevaMinas)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(chi_fincaGirasoles)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(chi_volcanIpala)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(zac_cerroMiramundos)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(zac_museoFerrocarril)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(zac_ValleDorado)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(zac_museoPalenGeolo)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(iz_arqueoQuirigua)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(iz_castilloSanFelipe)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(iz_lagoIzabal)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(iz_playaDorada)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(iz_rioDulce)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(iz_bahiaAmatique)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(iz_puntaPalma)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(iz_playaGraciosa)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(iz_biotopoChacon)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(iz_cayosDiablo)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pet_lagoItza)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_museoPopolVuh)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_museoArqueologia)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_mapaRelieve)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_mercadoCentral)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_museoFerrocarril)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_museoIxchel)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_museoNacionalArte)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_iglesiaCerritoCarmen)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_hipodromoNorte)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_kaminaljuyu)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_jardinBotanico)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_museoHolocausto)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_palacioNacional)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_zooAurora)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_catedralGuatemala)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(chi_parqueMontecristo)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pet_lagoItza)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_palacioNacional)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_zooAurora)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_catedralGuatemala)
CREATE (religioso)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_catedralGuatemala)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_museoPopolVuh)
CREATE (arqueologico)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pet_tikal)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pet_tikal)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pet_islaFlores)
CREATE (gastronomico)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pet_islaFlores)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pet_resBiosferaMaya)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pet_resBiosferaMaya)
CREATE (arqueologico)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pet_resBiosferaMaya)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pet_lagunaYaxha)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pet_pNacLagunaTigre)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pet_pNacSierraLacandon)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pet_lagunaPetexbatun)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pet_petencito)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pet_petencito)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pet_parqueActunKan)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pet_parqueActunKan)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pet_craterAzul)
CREATE (etnoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_museoArqueologia)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_museoArqueologia)
CREATE (arqueologico)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_museoArqueologia)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_mapaRelieve)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_mercadoCentral)
CREATE (gastronomico)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_mercadoCentral)
CREATE (etnoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_museoIxchel)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_museoIxchel)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_museoFerrocarril)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_museoNacionalArte)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_iglesiaCerritoCarmen)
CREATE (religioso)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_iglesiaCerritoCarmen)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_hipodromoNorte)
CREATE (deportivo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_hipodromoNorte)
CREATE (arqueologico)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_kaminaljuyu)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_kaminaljuyu)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_jardinBotanico)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_jardinBotanico)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_museoHolocausto)
CREATE (etnoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_museoHolocausto)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jut_lagoGuija)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jut_lagunaAtescatempa)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jut_playaMarina)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jut_volcanViboras)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jut_volcanViboras)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jut_volcanChingo)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jut_volcanChingo)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jut_volcanIxtepeque)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jut_volcanIxtepeque)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jut_volcanSuchitan)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jut_volcanSuchitan)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jut_volcanMoyuta)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jut_volcanMoyuta)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jut_cuevaAndaMira)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jut_cuevaAndaMira)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jal_cascadaTatasirire)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jal_cascadaTatasirire)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jal_lagunaAchiotes)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jal_ruinasIngenioAyarza)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jal_iglesiaJilotepeque)
CREATE (religioso)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jal_iglesiaJilotepeque)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jal_lagunaHoyo)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jal_volcanJumay)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jal_volcanJumay)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jal_volcanAlzatete)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jal_volcanAlzatete)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(chi_basilicaEsquipulas)
CREATE (religioso)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(chi_basilicaEsquipulas)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(chi_cuevaMinas)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(chi_fincaGirasoles)
CREATE (etnoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(chi_cuevaMinas)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(chi_volcanIpala)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(chi_volcanIpala)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(chi_parqueMontecristo)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(chi_parqueMontecristo)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(zac_cerroMiramundos)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(zac_museoFerrocarril)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(zac_ValleDorado)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(zac_museoPalenGeolo)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(zac_museoPalenGeolo)
CREATE (arqueologico)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(iz_arqueoQuirigua)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(iz_castilloSanFelipe)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(iz_lagoIzabal)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(iz_lagoIzabal)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jut_lagunaAtescatempa)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jal_lagunaHoyo)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jal_lagunaAchiotes)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(iz_playaDorada)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(iz_playaDorada)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(iz_rioDulce)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(iz_rioDulce)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(iz_bahiaAmatique)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(iz_puntaPalma)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(iz_puntaPalma)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(iz_playaGraciosa)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(iz_playaGraciosa)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(iz_biotopoChacon)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(iz_biotopoChacon)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(iz_cayosDiablo)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(iz_cayosDiablo)