
CREATE (GTM:Pais {Nombre: 'Guatemala'})
CREATE (rpeten:Region {Nombre: 'Petén'})
CREATE (metropolitana:Region {Nombre: 'Metropolitana'})
CREATE (norte:Region {Nombre: 'Norte'})
CREATE (nororiente:Region {Nombre: 'Nororiente'})
CREATE (suroriente:Region {Nombre: 'Suroriente'})
CREATE (central:Region {Nombre: 'Central'})
CREATE (suroccidente:Region {Nombre: 'Suroccidente'})
CREATE (noroccidente:Region {Nombre: 'Noroccidente'})
CREATE (peten:Municipio {titulo: 'Petén'})
CREATE (cguatemala:Municipio {titulo: 'Ciudad de Guatemala'})
CREATE (altaVerapaz:Municipio {titulo: 'Alta Verapaz'})
CREATE (bajaVerapaz:Municipio {titulo: 'Baja Verapaz'})
CREATE (chiquimula:Municipio {titulo: 'Chiquimula'})
CREATE (elProgreso:Municipio {titulo: 'El Progreso'})
CREATE (izabal:Municipio {titulo: 'Izabal'})
CREATE (Zacapa:Municipio {titulo: 'Zacapa'})
CREATE (jalapa:Municipio {titulo: 'Jalapa'})
CREATE (jutiapa:Municipio {titulo: 'Jutiapa'})
CREATE (santaRosa:Municipio {titulo: 'Santa Rosa'})
CREATE (chimaltenango:Municipio {titulo: 'Chimaltenango'})
CREATE (escuintla:Municipio {titulo: 'Escuintla'})
CREATE (sacatepequez:Municipio {titulo: 'Sacatepéquez'})
CREATE (retalhuleu:Municipio {titulo: 'Retalhuleu'})
CREATE (sanMarcos:Municipio {titulo: 'San Marcos'})
CREATE (solola:Municipio {titulo: 'Sololá'})
CREATE (suchitepequez:Municipio {titulo: 'Suchitepéquez'})
CREATE (totonicapan:Municipio {titulo: 'Totonicapán'})
CREATE (quetzaltenango:Municipio {titulo: 'Quetzaltenango'})
CREATE (Huehue:Municipio {titulo: 'Huehuetenango'})
CREATE (frio:Clima {titulo: 'Frío'})
CREATE (calido:Clima {titulo: 'Cálido'})
CREATE (templado:Clima {titulo: 'Templado'})
CREATE (lluvioso:Clima {titulo: 'Lluvioso'})
CREATE (humedo:Clima {titulo: 'Húmedo'})
CREATE (gt_museoPopolVuh:Turismo {Lugar: 'Museo Popol Vuh', Presupuesto: 'Q'})
CREATE (pet_tikal:Turismo {Lugar: 'Tikal', Presupuesto: 'QQQ'})
CREATE (pet_islaFlores:Turismo {Lugar: 'Isla de Flores', Presupuesto: 'QQQQ'})
CREATE (pet_resBiosferaMaya:Turismo {Lugar: 'Reserva de la Biosfera Maya', Presupuesto: 'QQQ'})
CREATE (pet_lagunaYaxha:Turismo {Lugar: 'Laguna Yaxhá', Presupuesto: 'QQQ'})
CREATE (pet_pNacLagunaTigre:Turismo {Lugar: 'Parque Nacional Laguna del Tigre', Presupuesto: 'QQ'})
CREATE (pet_pNacSierraLacandon:Turismo {Lugar: 'Parque Nacional Sierra del Lacandón', Presupuesto: 'QQQ'})
CREATE (pet_lagunaPetexbatun:Turismo {Lugar: 'Laguna Petexbatun', Presupuesto: 'QQQ'})
CREATE (pet_petencito:Turismo {Lugar: 'Petencito', Presupuesto: 'QQQ'})
CREATE (pet_parqueActunKan:Turismo {Lugar: 'Parque Regional Actún Kan', Presupuesto: 'QQQ'})
CREATE (pet_craterAzul:Turismo {Lugar: 'Cráter Azul', Presupuesto: 'QQ'})
CREATE (gt_museoArqueologia:Turismo {Lugar: 'Museo Nacional de Arqueología y Etnología de Guatemala', Presupuesto: 'Q'})
CREATE (gt_mapaRelieve:Turismo {Lugar: 'Mapa en Relieve de Guatemala', Presupuesto: 'Q'})
CREATE (gt_mercadoCentral:Turismo {Lugar: 'Mercado Central', Presupuesto: 'QQ'})
CREATE (gt_museoFerrocarril:Turismo {Lugar: 'Museo del Ferrocarril de Guatemala', Presupuesto: 'Q'})
CREATE (gt_museoIxchel:Turismo {Lugar: 'Museo Ixchel del Traje Indígena', Presupuesto: 'Q'})
CREATE (gt_museoNacionalArte:Turismo {Lugar: 'Museo Nacional de Arte Moderno Carlos Mérida', Presupuesto: 'Q'})
CREATE (gt_iglesiaCerritoCarmen:Turismo {Lugar: 'Iglesia del Cerrito del Carmen', Presupuesto: 'Q'})
CREATE (gt_hipodromoNorte:Turismo {Lugar: 'Hipódromo del Norte', Presupuesto: 'Q'})
CREATE (gt_kaminaljuyu:Turismo {Lugar: 'Zona Arqueológica Kaminaljuyu', Presupuesto: 'Q'})
CREATE (gt_jardinBotanico:Turismo {Lugar: 'Jardín Botánico de Guatemala', Presupuesto: 'Q'})
CREATE (gt_museoHolocausto:Turismo {Lugar: 'Museo del Holocausto Guatemala', Presupuesto: 'Q'})
CREATE (jut_lagoGuija:Turismo {Lugar: 'Lago de Guija', Presupuesto: 'QQ'})
CREATE (jut_lagunaAtescatempa:Turismo {Lugar: 'Laguna Atescatempa', Presupuesto: 'QQ'})
CREATE (jut_playaMarina:Turismo {Lugar: 'Playas Marinas', Presupuesto: 'QQ'})
CREATE (jut_volcanViboras:Turismo {Lugar: 'Volcán de las Víboras', Presupuesto: 'QQ'})
CREATE (jut_volcanChingo:Turismo {Lugar: 'Volcán Chingo', Presupuesto: 'QQ'})
CREATE (jut_volcanIxtepeque:Turismo {Lugar: 'Volcán Ixtepeque', Presupuesto: 'QQ'})
CREATE (jut_volcanSuchitan:Turismo {Lugar: 'Volcán Suchitán', Presupuesto: 'QQ'})
CREATE (jut_volcanMoyuta:Turismo {Lugar: 'Volcán Moyuta', Presupuesto: 'QQ'})
CREATE (jut_cuevaAndaMira:Turismo {Lugar: 'Cueva de Anda Mirá', Presupuesto: 'QQ'})
CREATE (jal_cascadaTatasirire:Turismo {Lugar: 'Cascadas de Tatasirire', Presupuesto: 'QQ'})
CREATE (jal_lagunaAchiotes:Turismo {Lugar: 'Laguna de Achiotes Jumay', Presupuesto: 'QQ'})
CREATE (jal_ruinasIngenioAyarza:Turismo {Lugar: 'Ruinas Coloniales del Ingenio Ayarza', Presupuesto: 'QQ'})
CREATE (jal_iglesiaJilotepeque:Turismo {Lugar: 'Iglesia Colonial de San Luis Jilotepeque', Presupuesto: 'QQ'})
CREATE (jal_lagunaHoyo:Turismo {Lugar: 'Laguna del Hoyo', Presupuesto: 'QQ'})
CREATE (jal_volcanJumay:Turismo {Lugar: 'Volcán Jumay', Presupuesto: 'QQ'})
CREATE (jal_volcanAlzatete:Turismo {Lugar: 'Volcán Alzatete', Presupuesto: 'QQ'})
CREATE (chi_basilicaEsquipulas:Turismo {Lugar: 'Basílica de Esquipulas', Presupuesto: 'QQ'})
CREATE (chi_cuevaMinas:Turismo {Lugar: 'La cueva de las Minas', Presupuesto: 'QQ'})
CREATE (chi_fincaGirasoles:Turismo {Lugar: 'Finca Los Girasoles', Presupuesto: 'QQ'})
CREATE (chi_volcanIpala:Turismo {Lugar: 'Volcán de Ipala', Presupuesto: 'QQ'})
CREATE (chi_parqueMontecristo:Turismo {Lugar: 'Parque Nacional Montecristo o Trifinio', Presupuesto: 'QQ'})
CREATE (zac_cerroMiramundos:Turismo {Lugar: 'Cerro Miramundo', Presupuesto: 'QQ'})
CREATE (zac_museoFerrocarril:Turismo {Lugar: 'Museo del Ferrocarril Zacapa', Presupuesto: 'QQ'})
CREATE (zac_ValleDorado:Turismo {Lugar: 'Turicentro Valle Dorado', Presupuesto: 'QQ'})
CREATE (zac_museoPalenGeolo:Turismo {Lugar: 'Museo de Paleontología, Arqueología y Geología', Presupuesto: 'QQ'})
CREATE (iz_arqueoQuirigua:Turismo {Lugar: 'Sitio Arqueológico de Quiriguá', Presupuesto: 'QQ'})
CREATE (iz_castilloSanFelipe:Turismo {Lugar: 'Castillo de San Felipe de Lara', Presupuesto: 'QQ'})
CREATE (iz_lagoIzabal:Turismo {Lugar: 'Lago de Izabal', Presupuesto: 'QQ'})
CREATE (iz_playaDorada:Turismo {Lugar: 'Playa Dorada', Presupuesto: 'QQ'})
CREATE (iz_rioDulce:Turismo {Lugar: 'Río Dulce', Presupuesto: 'QQ'})
CREATE (iz_bahiaAmatique:Turismo {Lugar: 'Bahía de Amatique', Presupuesto: 'QQ'})
CREATE (iz_puntaPalma:Turismo {Lugar: 'Punta de Palma', Presupuesto: 'QQ'})
CREATE (iz_playaGraciosa:Turismo {Lugar: 'Playa La Graciosa', Presupuesto: 'QQ'})
CREATE (iz_biotopoChacon:Turismo {Lugar: 'Biotopo Protegido Chacón Machacas', Presupuesto: 'QQ'})
CREATE (iz_cayosDiablo:Turismo {Lugar: 'Los Cayos del Diablo', Presupuesto: 'QQ'})
CREATE (san_lagunaayarza:Turismo {Lugar: 'Laguna de Ayarza', Presupuesto: 'QQ'})
CREATE (san_laslisas:Turismo {Lugar: 'Playa Las Lisas', Presupuesto: 'QQ'})
CREATE (san_lagunaixpaco:Turismo {Lugar: 'Laguna Ixpaco', Presupuesto: 'QQ'})
CREATE (san_monterrico:Turismo {Lugar: 'Playa Monterrico', Presupuesto: 'QQ'})
CREATE (san_canaldechiquimulilla:Turismo {Lugar: 'Canal De Chiquimulilla', Presupuesto: 'QQ'})
CREATE (san_cascadasdelosamates:Turismo {Lugar: 'Cascadas de los Amates', Presupuesto: 'QQ'})
CREATE (san_hawaii:Turismo {Lugar: 'Playa El Hawaii', Presupuesto: 'QQ'})
CREATE (san_lagunaelpino:Turismo {Lugar: 'Laguna El Pino', Presupuesto: 'QQ'})
CREATE (san_volcantecuamburro:Turismo {Lugar: 'Volcan Tecuamburro', Presupuesto: 'QQ'})
CREATE (san_cascadalaconcepcion:Turismo {Lugar: 'Cascada La Concepcion', Presupuesto: 'QQ'})
CREATE (san_volcancruzquemada:Turismo {Lugar: 'Volcan Cruz Quemada', Presupuesto: 'QQ'})
CREATE (san_riolosesclavos:Turismo {Lugar: 'Rio Los Esclavos', Presupuesto: 'QQ'})
CREATE (chi_iximche:Turismo {Lugar: 'Iximche', Presupuesto: 'QQ'})
CREATE (chi_lagunachicoy:Turismo {Lugar: 'Laguna Chichoy', Presupuesto: 'QQ'})
CREATE (chi_casaxaraymolino:Turismo {Lugar: 'Casa Xara y Molino', Presupuesto: 'QQ'})
CREATE (chi_volcandefuego:Turismo {Lugar: 'Volcan de Fuego', Presupuesto: 'QQ'})
CREATE (chi_galeriadeartetzutujil:Turismo {Lugar: 'Galeria de Arte Txutujil', Presupuesto: 'QQ'})
CREATE (chi_mixcoviejo:Turismo {Lugar: 'Mixco Viejo', Presupuesto: 'QQ'})
CREATE (chi_volcandeacatenango:Turismo {Lugar: 'Volcan de Acatenango', Presupuesto: 'QQ'})
CREATE (chi_fincacalerachichavac:Turismo {Lugar: 'Finca Caleras Chichavac', Presupuesto: 'QQ'})
CREATE (chi_patzun:Turismo {Lugar: 'Patzun', Presupuesto: 'QQ'})
CREATE (ret_takalikabaj:Turismo {Lugar: 'Takalik Abaj', Presupuesto: 'QQ'})
CREATE (ret_museoxulik:Turismo {Lugar: 'Museo Xulik', Presupuesto: 'QQ'})
CREATE (ret_reservapatrocinio:Turismo {Lugar: 'Reserva Patrocinio', Presupuesto: 'QQ'})
CREATE (ret_xocomil:Turismo {Lugar: 'Xocomil', Presupuesto: 'QQ'})
CREATE (ret_champerico:Turismo {Lugar: 'Playa de Champerico', Presupuesto: 'QQ'})
CREATE (ret_takalikmayalodge:Turismo {Lugar: 'Takalik Maya Lodge', Presupuesto: 'QQ'})
CREATE (ret_xetulul:Turismo {Lugar: 'Xetulul', Presupuesto: 'QQ'})
CREATE (san_cataratalaigualdad:Turismo {Lugar: 'Catarata La Igualdad', Presupuesto: 'QQ'})
CREATE (san_parqueregionalmunicipalastillero:Turismo {Lugar: 'Parque Regional Municipal Astillero', Presupuesto: 'QQ'})
CREATE (san_refugiodelquetzal:Turismo {Lugar: 'Refugio del Quetzal', Presupuesto: 'QQ'})
CREATE (san_volcantajumulco:Turismo {Lugar: 'Volcan Tajumulco', Presupuesto: 'QQ'})
CREATE (san_montainbike:Turismo {Lugar: 'Mountain Bike', Presupuesto: 'QQ'})
CREATE (san_tilapa:Turismo {Lugar: 'Playas de Tilapa', Presupuesto: 'QQ'})
CREATE (san_volcantacana:Turismo {Lugar: 'Volcán Tacana', Presupuesto: 'QQ'})
CREATE (sol_miradorixchel:Turismo {Lugar: 'Mirador Ixchel', Presupuesto: 'QQ'})
CREATE (sol_santacruzlalaguna:Turismo {Lugar: 'Santa Cruz La Laguna', Presupuesto: 'QQ'})
CREATE (sol_sanjuanlalaguna:Turismo {Lugar: 'San Juan La Laguna', Presupuesto: 'QQ'})
CREATE (so_theyogaforest:Turismo {Lugar: 'The Yogo Forest', Presupuesto: 'QQ'})
CREATE (sol_cafeloco:Turismo {Lugar: 'Café Loco', Presupuesto: 'QQ'})
CREATE (sol_miradorrostromaya:Turismo {Lugar: 'Mirador Rostro Maya', Presupuesto: 'QQ'})
CREATE (sol_sanperdrolalaguna:Turismo {Lugar: 'San Pedro La Laguna', Presupuesto: 'QQ'})
CREATE (sol_museolacustre:Turismo {Lugar: 'Museo Lacustre', Presupuesto: 'QQ'})
CREATE (sol_clubvenaca:Turismo {Lugar: 'Club Ven Aca', Presupuesto: 'QQ'})
CREATE (sol_sanantoniopalopo:Turismo {Lugar: 'San Antonio Palopo', Presupuesto: 'QQ'})
CREATE (sol_lacasadedonmemo:Turismo {Lugar: 'La Casa De Don Memo', Presupuesto: 'QQ'})
CREATE (sol_santiagoatitlan:Turismo {Lugar: 'Santiago Atitlan', Presupuesto: 'QQ'})
CREATE (sol_reservanaturalatitlan:Turismo {Lugar: 'Reserva Natural Atitlan', Presupuesto: 'QQ'})
CREATE (sol_yatchclubatitlan:Turismo {Lugar: 'Yatch Club Atitlán', Presupuesto: 'QQ'})
CREATE (sol_sanmarcoslalaguna:Turismo {Lugar: 'San Marcos La Laguna', Presupuesto: 'QQ'})
CREATE (sol_santacatarinapalopo:Turismo {Lugar: 'Santa Catarina Palopó', Presupuesto: 'QQ'})
CREATE (sol_cerrotzankujil:Turismo {Lugar: 'Cerro Tzankujil', Presupuesto: 'QQ'})
CREATE (sol_sanlucastoliman:Turismo {Lugar: 'San Lucas Tolimán', Presupuesto: 'QQ'})
CREATE (sol_miradordeatitlan:Turismo {Lugar: 'Mirador de Atitlán', Presupuesto: 'QQ'})
CREATE (sol_catarataensolola:Turismo {Lugar: 'Catarata en Sololá', Presupuesto: 'QQ'})
CREATE (sol_volcansanpedro:Turismo {Lugar: 'Parque Ecológico Volcán San Pedro', Presupuesto: 'QQ'})
CREATE (sol_nahuala:Turismo {Lugar: 'Nahualá', Presupuesto: 'QQ'})
CREATE (suc_cafechocola:Turismo {Lugar: 'Beneficio de café Chocolá', Presupuesto: 'QQ'})
CREATE (suc_elchorrosdelcarme:Turismo {Lugar: 'El Chorros del Carmen', Presupuesto: 'QQ'})
CREATE (suc_relojcentenariochocola:Turismo {Lugar: 'Reloj Centenario Chocolá', Presupuesto: 'QQ'})
CREATE (suc_cerrocabezadeburro:Turismo {Lugar: 'Cerro Cabeza de Burro', Presupuesto: 'QQ'})
CREATE (suc_chiquistepeque:Turismo {Lugar: 'Playa de Chiquistepeque', Presupuesto: 'QQ'})
CREATE (suc_fincalasnubes:Turismo {Lugar: 'Finca Las Nubes', Presupuesto: 'QQ'})
CREATE (tot_elaprisco:Turismo {Lugar: 'Sendero Ecológico El Aprisco', Presupuesto: 'QQ'})
CREATE (tot_riscosdemomostenango:Turismo {Lugar: 'Riscos de Momostenango', Presupuesto: 'QQ'})
CREATE (tot_miradorcerropaclom:Turismo {Lugar: 'Mirador Cerro Paclom', Presupuesto: 'QQ'})
CREATE (tot_igleasiasanandresxecul:Turismo {Lugar: 'Iglesia San Andrés Xecul', Presupuesto: 'QQ'})
CREATE (tot_mercadosanfranciscoelalto:Turismo {Lugar: 'Mercado San Francisco El Alto', Presupuesto: 'QQ'})
CREATE (tot_cascadapatrubala:Turismo {Lugar: 'Cascada Patrubalá', Presupuesto: 'QQ'})
CREATE (tot_parqueecologicochajilsiwan:Turismo {Lugar: 'Parque Ecológico Chajil Siwan', Presupuesto: 'QQ'})
CREATE (tot_volcancuxliquel:Turismo {Lugar: 'Volcán Cuxliquel', Presupuesto: 'QQ'})
CREATE (tot_sancristobal:Turismo {Lugar: 'San Cristóbal', Presupuesto: 'QQ'})
CREATE (tot_momostenango:Turismo {Lugar: 'Momostenango,', Presupuesto: 'QQ'})
CREATE (tot_sanfranciscoelalto:Turismo {Lugar: 'San Francisco El Alto', Presupuesto: 'QQ'})
CREATE (tot_cuevasdesanmiguel:Turismo {Lugar: 'Cuevas de San Miguel', Presupuesto: 'QQ'})
CREATE (tot_aguastermalessanbartolo:Turismo {Lugar: 'Aguas termales San Bartolo', Presupuesto: 'QQ'})
CREATE (tot_nueveriscos:Turismo {Lugar: 'Nueve Sillas', Presupuesto: 'QQ'})
CREATE (que_fuentesgeorginas:Turismo {Lugar: 'Fuentes Georginas', Presupuesto: 'QQ'})
CREATE (que_ermitadelaconcepcionsalcaja:Turismo {Lugar: 'Ermita de la Concepción Salcajá', Presupuesto: 'QQ'})
CREATE (que_elviejopalmar:Turismo {Lugar: 'El Viejo Palmar', Presupuesto: 'QQ'})
CREATE (que_museodelferrocarrildelosaltos:Turismo {Lugar: 'Museo del Ferrocarril de los Altos', Presupuesto: 'QQ'})
CREATE (QUE_LAGUNAYVOLCANDECHICABAL:Turismo {Lugar: 'Laguna y volcán de Chicabal', Presupuesto: 'QQ'})
CREATE (que_cerroelbaul:Turismo {Lugar: 'Cerro El Baúl', Presupuesto: 'QQ'})
CREATE (que_templominerva:Turismo {Lugar: 'Templo Minerva', Presupuesto: 'QQ'})
CREATE (que_casadelaculturanoj:Turismo {Lugar: 'Casa de la Cultura Noj', Presupuesto: 'QQ'})
CREATE (que_volcansantamaria:Turismo {Lugar: 'Volcán Santa María', Presupuesto: 'QQ'})
CREATE (que_museodelahistorianatural:Turismo {Lugar: 'Museo de Historia Natural', Presupuesto: 'QQ'})
CREATE (que_pasajeenriquez:Turismo {Lugar: 'Pasaje Enríquez', Presupuesto: 'QQ'})
CREATE (que_lascumbresecosaunas:Turismo {Lugar: 'Las Cumbres Eco Saunas', Presupuesto: 'QQ'})
CREATE (que_museoixkikdeltrajemaya:Turismo {Lugar: 'Museo Ixkik del Traje Maya', Presupuesto: 'QQ'})
CREATE (que_teatromunicipal:Turismo {Lugar: 'Teatro Municipal', Presupuesto: 'QQ'})
CREATE (que_volcansantiaguito:Turismo {Lugar: 'Volcán Santiaguito', Presupuesto: 'QQ'})
CREATE (que_volcancerroquemado:Turismo {Lugar: 'Volcán Cerro Quemado', Presupuesto: 'QQ'})
CREATE (que_iglesiasannicolas:Turismo {Lugar: 'Iglesia San Nicolás', Presupuesto: 'QQ'})
CREATE (que_volcanzunil:Turismo {Lugar: 'Volcán Zunil', Presupuesto: 'QQ'})
CREATE (hue_cenotesdecandelaria:Turismo {Lugar: 'Cenotes de Candelaria', Presupuesto: 'QQ'})
CREATE (hue_lagunamaxbal:Turismo {Lugar: 'Laguna Maxbal', Presupuesto: 'QQ'})
CREATE (hue_rioazul:Turismo {Lugar: 'Río Azul', Presupuesto: 'QQ'})
CREATE (hue_lagunabrava:Turismo {Lugar: 'Laguna Brava', Presupuesto: 'QQ'})
CREATE (hue_ruinasdezaculeu:Turismo {Lugar: 'Ruinas de Zaculeu', Presupuesto: 'QQ'})
CREATE (hue_elcimarron:Turismo {Lugar: 'El Cimarrón', Presupuesto: 'QQ'})
CREATE (hue_senderoecologicolameceta:Turismo {Lugar: 'Sendero Ecológico La Maceta', Presupuesto: 'QQ'})
CREATE (hue_rioquisil:Turismo {Lugar: 'Río Quisil', Presupuesto: 'QQ'})
CREATE (hue_fincachacula:Turismo {Lugar: 'Posada Rural Finca Chaculá', Presupuesto: 'QQ'})
CREATE (hue_lagunamagdalena:Turismo {Lugar: 'Laguna Magdalena', Presupuesto: 'QQ'})
CREATE (hue_miradordiéguezolaverri:Turismo {Lugar: 'Mirador Diéguez Olaverri', Presupuesto: 'QQ'})
CREATE (hue_unicornioazul:Turismo {Lugar: 'Posada Rural y Ecuestre Unicornio Azul', Presupuesto: 'QQ'})
CREATE (hue_elmamut:Turismo {Lugar: 'El Mamut', Presupuesto: 'QQ'})
CREATE (hue_puedracuache:Turismo {Lugar: 'La Piedra Cuache', Presupuesto: 'QQ'})
CREATE (hue_cuevaselresumidero:Turismo {Lugar: 'Cuevas El Resumidero', Presupuesto: 'QQ'})
CREATE (pro_sierraMinas:Turismo {Lugar: 'La Sierra de las Minas', Presupuesto: 'QQ'})
CREATE (pro_aguasTermanes:Turismo {Lugar: 'Aguas Termales del Río Los Plátanos', Presupuesto: 'QQ'})
CREATE (pro_cerroPino:Turismo {Lugar: 'Cerro del Pino', Presupuesto: 'QQ'})
CREATE (pro_parAcuaticoGuastatoya:Turismo {Lugar: 'Parque Acuático Guastatoya', Presupuesto: 'QQ'})
CREATE (esc_pacaya:Turismo {Lugar: 'Volcán de Pacaya', Presupuesto: 'QQ'})
CREATE (esc_ceibaPentandra:Turismo {Lugar: 'Ceiba Pentandra', Presupuesto: 'QQ'})
CREATE (esc_grutasSanPedro:Turismo {Lugar: 'Grutas San Pedro Mártir', Presupuesto: 'QQ'})
CREATE (esc_ElPenion:Turismo {Lugar: 'El Peñon', Presupuesto: 'QQ'})
CREATE (esc_playaConacaste:Turismo {Lugar: 'Playa El Conacaste', Presupuesto: 'QQ'})
CREATE (esc_playaSemillero:Turismo {Lugar: 'Playa El Semillero', Presupuesto: 'QQ'})
CREATE (esc_playaRamaBlanca:Turismo {Lugar: 'Playa San José Rama Blanca', Presupuesto: 'QQ'})
CREATE (esc_playaparedon:Turismo {Lugar: 'Playa el Paredón', Presupuesto: 'QQ'})
CREATE (esc_autoSafari:Turismo {Lugar: 'Auto Safari Chapín', Presupuesto: 'QQ'})
CREATE (esc_parqueCalderas:Turismo {Lugar: 'Parque Nacional Calderas', Presupuesto: 'QQ'})
CREATE (esc_museoCotzumalguapa:Turismo {Lugar: 'Museo Cultural Cotzumalguapa', Presupuesto: 'QQ'})
CREATE (sac_volcanAgua:Turismo {Lugar: 'Volcán de Agua', Presupuesto: 'QQ'})
CREATE (sac_iglesiaJocotenango:Turismo {Lugar: 'Iglesia de Jocotenango', Presupuesto: 'QQ'})
CREATE (sac_mercadoSanLucas:Turismo {Lugar: 'Mercado de San Lucas', Presupuesto: 'QQ'})
CREATE (sac_mercadoArtesanias:Turismo {Lugar: 'Mercado de Artesanías', Presupuesto: 'QQ'})
CREATE (sac_museoArmas:Turismo {Lugar: 'Museo De Santiago de Los Caballeros', Presupuesto: 'QQ'})
CREATE (sac_museoLibro:Turismo {Lugar: 'Museo del Libro Antiguo', Presupuesto: 'QQ'})
CREATE (sac_muesoArteColonial:Turismo {Lugar: 'Museo de Arte Colonial', Presupuesto: 'QQ'})
CREATE (sac_museSantoDomingo:Turismo {Lugar: 'Museo Casa Santo Domingo', Presupuesto: 'QQ'})
CREATE (sac_museoPalacioArzobispal:Turismo {Lugar: 'Museo Del Palacio Arzobispal, San Juan El Obispo', Presupuesto: 'QQ'})
CREATE (sac_ruinasDeCompania:Turismo {Lugar: 'Ruinas de la Compañía de Jesús', Presupuesto: 'QQ'})
CREATE (sac_catedralSanJose:Turismo {Lugar: 'Catedral San José', Presupuesto: 'QQ'})
CREATE (sac_conventoSantaClara:Turismo {Lugar: 'Convento de Santa Clara', Presupuesto: 'QQ'})
CREATE (sac_conventoCapuchinas:Turismo {Lugar: 'Convento de Capuchinas', Presupuesto: 'QQ'})
CREATE (sac_iglesiaConventoMerced:Turismo {Lugar: 'Iglesia y Convento de la Merced', Presupuesto: 'QQ'})
CREATE (sac_claustroSanJeronimo:Turismo {Lugar: 'Claustro de San Jerónimo', Presupuesto: 'QQ'})
CREATE (aver_semucChampey:Turismo {Lugar: 'Semuc Champey', Presupuesto: 'QQQ'})
CREATE (aver_lagLachua:Turismo {Lugar: 'Laguna Lachúa', Presupuesto: 'QQ'})
CREATE (aver_biotopoQuetzal:Turismo {Lugar: 'Biotopo del Quetzal', Presupuesto: 'QQ'})
CREATE (aver_grutasLanquin:Turismo {Lugar: 'Parque Nacional Grutas de Lanquín', Presupuesto: 'QQ'})
CREATE (aver_hunNalYe:Turismo {Lugar: 'Hun Nal Ye', Presupuesto: 'QQ'})
CREATE (aver_grutasReyMarcos:Turismo {Lugar: 'Grutas del Rey Marcos', Presupuesto: 'QQ'})
CREATE (aver_cuevasSetzol:Turismo {Lugar: 'Cuevas De Setzol', Presupuesto: 'QQ'})
CREATE (aver_cuevasBombilPek:Turismo {Lugar: 'Cuevas de Bombil Pek', Presupuesto: 'QQ'})
CREATE (ever_ParqueCentralCoban:Turismo {Lugar: 'Parque Central Cobán', Presupuesto: 'QQ'})
CREATE (ever_cuevasCandelaria:Turismo {Lugar: 'Cuevas de Candelaria Mucbihá', Presupuesto: 'QQ'})
CREATE (bver_saltoChilasco:Turismo {Lugar: 'Salto de Chilascó', Presupuesto: 'QQ'})
CREATE (bver_museoRabinalAchi:Turismo {Lugar: 'Museo Comunitario Rabinal Achi', Presupuesto: 'QQ'})
CREATE (bver_parroquiaMiguelArcangel:Turismo {Lugar: 'Parroquia San Miguel Arcángel', Presupuesto: 'QQ'})
CREATE (bver_museoKomoon:Turismo {Lugar: 'Sitio Arqueológico Museo Komoon', Presupuesto: 'QQ'})
CREATE (bver_cataratasChupadero:Turismo {Lugar: 'Cataratas El Chupadero', Presupuesto: 'QQ'})
CREATE (bver_rioEscondido:Turismo {Lugar: 'Río Escondido', Presupuesto: 'QQ'})
CREATE (bver_museoTrapiche:Turismo {Lugar: 'Museo Regional del Trapiche', Presupuesto: 'QQ'})
CREATE (pet_lagoItza:Turismo {Lugar: 'Lago Petén Itza', Presupuesto: 'QQ'})
CREATE (gt_palacioNacional:Turismo {Lugar: 'Palacio Nacional de la Cultura', Presupuesto: 'Q'})
CREATE (gt_zooAurora:Turismo {Lugar: 'Zoológico La Aurora', Presupuesto: 'QQ'})
CREATE (gt_catedralGuatemala:Turismo {Lugar: 'Catedral de Ciudad de Guatemala', Presupuesto: 'Q'})
CREATE (qeqchi:Idioma {titulo: 'Qeqchi'})
CREATE (pocomchi:Idioma {titulo: 'Pocomchi'})
CREATE (achi:Idioma {titulo: 'Achí'})
CREATE (kiche:Idioma {titulo: 'Kiche'})
CREATE (espaniol:Idioma {titulo: 'Español'})
CREATE (kaqchikel:Idioma {titulo: 'Kaqchikel'})
CREATE (pocoman:Idioma {titulo: 'Pocoman'})
CREATE (chorti:Idioma {titulo: 'Chortí'})
CREATE (garifuna:Idioma {titulo: 'Garífuna'})
CREATE (quekchi:Idioma {titulo: 'Quekchí'})
CREATE (mam:Idioma {titulo: 'Mam'})
CREATE (tzutujil:Idioma {titulo: 'Tzutujil'})
CREATE (ecoturismo:Tipo_Turismo {titulo: 'Ecoturismo'})
CREATE (comunitario:Tipo_Turismo {titulo: 'Comunitario'})
CREATE (cultural:Tipo_Turismo {titulo: 'Cultural'})
CREATE (gastronomico:Tipo_Turismo {titulo: 'Gastronómico'})
CREATE (agroturismo:Tipo_Turismo {titulo: 'Agroturismo'})
CREATE (aventura:Tipo_Turismo {titulo: 'Aventura'})
CREATE (deportivo:Tipo_Turismo {titulo: 'Deportivo'})
CREATE (etnoturismo:Tipo_Turismo {titulo: 'Etnoturismo'})
CREATE (religioso:Tipo_Turismo {titulo: 'Religioso'})
CREATE (arqueologico:Tipo_Turismo {titulo: 'Arqueológico'})

CREATE (rpeten)-[:REGION_PAIS {roles:['Region Pais']}]->(GTM)
CREATE (metropolitana)-[:REGION_PAIS {roles:['Region Pais']}]->(GTM)
CREATE (norte)-[:REGION_PAIS {roles:['Region Pais']}]->(GTM)
CREATE (nororiente)-[:REGION_PAIS {roles:['Region Pais']}]->(GTM)
CREATE (suroriente)-[:REGION_PAIS {roles:['Region Pais']}]->(GTM)
CREATE (central)-[:REGION_PAIS {roles:['Region Pais']}]->(GTM)
CREATE (suroccidente)-[:REGION_PAIS {roles:['Region Pais']}]->(GTM)
CREATE (noroccidente)-[:REGION_PAIS {roles:['Region Pais']}]->(GTM)
CREATE (rpeten)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(peten)
CREATE (metropolitana)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(cguatemala)
CREATE (norte)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(altaVerapaz)
CREATE (norte)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(bajaVerapaz)
CREATE (nororiente)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(chiquimula)
CREATE (nororiente)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(elProgreso)
CREATE (nororiente)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(izabal)
CREATE (nororiente)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(Zacapa)
CREATE (suroriente)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(jalapa)
CREATE (suroriente)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(jutiapa)
CREATE (suroriente)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(santaRosa)
CREATE (central)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(chimaltenango)
CREATE (central)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(escuintla)
CREATE (central)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(sacatepequez)
CREATE (suroccidente)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(retalhuleu)
CREATE (suroccidente)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(sanMarcos)
CREATE (suroccidente)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(solola)
CREATE (suroccidente)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(suchitepequez)
CREATE (suroccidente)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(totonicapan)
CREATE (suroccidente)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(quetzaltenango)
CREATE (noroccidente)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(Huehue)
CREATE (cguatemala)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(gt_museoPopolVuh)
CREATE (peten)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(pet_tikal)
CREATE (peten)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(pet_islaFlores)
CREATE (peten)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(pet_resBiosferaMaya)
CREATE (peten)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(pet_lagunaYaxha)
CREATE (peten)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(pet_pNacLagunaTigre)
CREATE (peten)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(pet_pNacSierraLacandon)
CREATE (peten)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(pet_lagunaPetexbatun)
CREATE (peten)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(pet_petencito)
CREATE (peten)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(pet_parqueActunKan)
CREATE (peten)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(pet_craterAzul)
CREATE (cguatemala)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(gt_museoArqueologia)
CREATE (cguatemala)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(gt_mapaRelieve)
CREATE (cguatemala)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(gt_mercadoCentral)
CREATE (cguatemala)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(gt_museoFerrocarril)
CREATE (cguatemala)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(gt_museoIxchel)
CREATE (cguatemala)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(gt_museoNacionalArte)
CREATE (cguatemala)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(gt_iglesiaCerritoCarmen)
CREATE (cguatemala)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(gt_hipodromoNorte)
CREATE (cguatemala)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(gt_kaminaljuyu)
CREATE (cguatemala)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(gt_jardinBotanico)
CREATE (cguatemala)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(gt_museoHolocausto)
CREATE (jutiapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jut_lagoGuija)
CREATE (jutiapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jut_lagunaAtescatempa)
CREATE (jutiapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jut_playaMarina)
CREATE (jutiapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jut_volcanViboras)
CREATE (jutiapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jut_volcanChingo)
CREATE (jutiapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jut_volcanIxtepeque)
CREATE (jutiapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jut_volcanSuchitan)
CREATE (jutiapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jut_volcanMoyuta)
CREATE (jutiapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jut_cuevaAndaMira)
CREATE (jalapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jal_cascadaTatasirire)
CREATE (jalapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jal_lagunaAchiotes)
CREATE (jalapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jal_ruinasIngenioAyarza)
CREATE (jalapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jal_iglesiaJilotepeque)
CREATE (jalapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jal_lagunaHoyo)
CREATE (jalapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jal_volcanJumay)
CREATE (jalapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jal_volcanAlzatete)
CREATE (chiquimula)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(chi_basilicaEsquipulas)
CREATE (chiquimula)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(chi_cuevaMinas)
CREATE (chiquimula)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(chi_fincaGirasoles)
CREATE (chiquimula)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(chi_volcanIpala)
CREATE (chiquimula)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(chi_parqueMontecristo)
CREATE (Zacapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(zac_cerroMiramundos)
CREATE (Zacapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(zac_museoFerrocarril)
CREATE (Zacapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(zac_ValleDorado)
CREATE (Zacapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(zac_museoPalenGeolo)
CREATE (izabal)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(iz_arqueoQuirigua)
CREATE (izabal)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(iz_castilloSanFelipe)
CREATE (izabal)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(iz_lagoIzabal)
CREATE (izabal)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(iz_playaDorada)
CREATE (izabal)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(iz_rioDulce)
CREATE (izabal)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(iz_bahiaAmatique)
CREATE (izabal)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(iz_puntaPalma)
CREATE (izabal)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(iz_playaGraciosa)
CREATE (izabal)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(iz_biotopoChacon)
CREATE (izabal)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(iz_cayosDiablo)
CREATE (santaRosa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_lagunaayarza)
CREATE (santaRosa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_laslisas)
CREATE (santaRosa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_lagunaixpaco)
CREATE (santaRosa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_monterrico)
CREATE (santaRosa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_canaldechiquimulilla)
CREATE (santaRosa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_cascadasdelosamates)
CREATE (santaRosa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_hawaii)
CREATE (santaRosa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_lagunaelpino)
CREATE (santaRosa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_volcantecuamburro)
CREATE (santaRosa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_cascadalaconcepcion)
CREATE (santaRosa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_volcancruzquemada)
CREATE (santaRosa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_riolosesclavos)
CREATE (chimaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(chi_iximche)
CREATE (chimaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(chi_lagunachicoy)
CREATE (chimaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(chi_casaxaraymolino)
CREATE (chimaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(chi_volcandefuego)
CREATE (chimaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(chi_galeriadeartetzutujil)
CREATE (chimaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(chi_mixcoviejo)
CREATE (chimaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(chi_volcandeacatenango)
CREATE (chimaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(chi_fincacalerachichavac)
CREATE (chimaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(chi_patzun)
CREATE (retalhuleu)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(ret_takalikabaj)
CREATE (retalhuleu)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(ret_museoxulik)
CREATE (retalhuleu)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(ret_reservapatrocinio)
CREATE (retalhuleu)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(ret_xocomil)
CREATE (retalhuleu)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(ret_champerico)
CREATE (retalhuleu)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(ret_takalikmayalodge)
CREATE (retalhuleu)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(ret_xetulul)
CREATE (sanMarcos)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_cataratalaigualdad)
CREATE (sanMarcos)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_parqueregionalmunicipalastillero)
CREATE (sanMarcos)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_refugiodelquetzal)
CREATE (sanMarcos)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_volcantajumulco)
CREATE (sanMarcos)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_montainbike)
CREATE (sanMarcos)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_tilapa)
CREATE (sanMarcos)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_volcantacana)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_miradorixchel)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_santacruzlalaguna)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_sanjuanlalaguna)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(so_theyogaforest)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_cafeloco)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_miradorrostromaya)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_sanperdrolalaguna)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_museolacustre)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_clubvenaca)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_sanantoniopalopo)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_lacasadedonmemo)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_santiagoatitlan)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_reservanaturalatitlan)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_yatchclubatitlan)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_sanmarcoslalaguna)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_santacatarinapalopo)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_cerrotzankujil)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_sanlucastoliman)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_miradordeatitlan)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_catarataensolola)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_volcansanpedro)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_nahuala)
CREATE (suchitepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(suc_cafechocola)
CREATE (suchitepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(suc_elchorrosdelcarme)
CREATE (suchitepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(suc_relojcentenariochocola)
CREATE (suchitepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(suc_cerrocabezadeburro)
CREATE (suchitepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(suc_chiquistepeque)
CREATE (suchitepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(suc_fincalasnubes)
CREATE (totonicapan)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(tot_elaprisco)
CREATE (totonicapan)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(tot_riscosdemomostenango)
CREATE (totonicapan)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(tot_miradorcerropaclom)
CREATE (totonicapan)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(tot_igleasiasanandresxecul)
CREATE (totonicapan)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(tot_mercadosanfranciscoelalto)
CREATE (totonicapan)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(tot_cascadapatrubala)
CREATE (totonicapan)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(tot_parqueecologicochajilsiwan)
CREATE (totonicapan)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(tot_volcancuxliquel)
CREATE (totonicapan)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(tot_sancristobal)
CREATE (totonicapan)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(tot_momostenango)
CREATE (totonicapan)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(tot_sanfranciscoelalto)
CREATE (totonicapan)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(tot_cuevasdesanmiguel)
CREATE (totonicapan)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(tot_aguastermalessanbartolo)
CREATE (totonicapan)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(tot_nueveriscos)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(que_fuentesgeorginas)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(que_ermitadelaconcepcionsalcaja)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(que_elviejopalmar)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(que_museodelferrocarrildelosaltos)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(QUE_LAGUNAYVOLCANDECHICABAL)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(que_cerroelbaul)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(que_templominerva)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(que_casadelaculturanoj)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(que_volcansantamaria)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(que_museodelahistorianatural)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(que_pasajeenriquez)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(que_lascumbresecosaunas)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(que_museoixkikdeltrajemaya)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(que_teatromunicipal)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(que_volcansantiaguito)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(que_volcancerroquemado)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(que_iglesiasannicolas)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(que_volcanzunil)
CREATE (Huehue)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(hue_cenotesdecandelaria)
CREATE (Huehue)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(hue_lagunamaxbal)
CREATE (Huehue)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(hue_rioazul)
CREATE (Huehue)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(hue_lagunabrava)
CREATE (Huehue)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(hue_ruinasdezaculeu)
CREATE (Huehue)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(hue_elcimarron)
CREATE (Huehue)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(hue_senderoecologicolameceta)
CREATE (Huehue)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(hue_rioquisil)
CREATE (Huehue)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(hue_fincachacula)
CREATE (Huehue)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(hue_lagunamagdalena)
CREATE (Huehue)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(hue_miradordiéguezolaverri)
CREATE (Huehue)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(hue_unicornioazul)
CREATE (Huehue)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(hue_elmamut)
CREATE (Huehue)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(hue_puedracuache)
CREATE (Huehue)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(hue_cuevaselresumidero)
CREATE (elProgreso)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(pro_sierraMinas)
CREATE (elProgreso)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(pro_aguasTermanes)
CREATE (elProgreso)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(pro_cerroPino)
CREATE (elProgreso)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(pro_parAcuaticoGuastatoya)
CREATE (escuintla)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(esc_pacaya)
CREATE (escuintla)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(esc_ceibaPentandra)
CREATE (escuintla)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(esc_grutasSanPedro)
CREATE (escuintla)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(esc_ElPenion)
CREATE (escuintla)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(esc_playaConacaste)
CREATE (escuintla)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(esc_playaSemillero)
CREATE (escuintla)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(esc_playaRamaBlanca)
CREATE (escuintla)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(esc_playaparedon)
CREATE (escuintla)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(esc_autoSafari)
CREATE (escuintla)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(esc_parqueCalderas)
CREATE (escuintla)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(esc_museoCotzumalguapa)
CREATE (sacatepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sac_volcanAgua)
CREATE (sacatepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sac_iglesiaJocotenango)
CREATE (sacatepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sac_mercadoSanLucas)
CREATE (sacatepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sac_mercadoArtesanias)
CREATE (sacatepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sac_museoArmas)
CREATE (sacatepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sac_museoLibro)
CREATE (sacatepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sac_muesoArteColonial)
CREATE (sacatepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sac_museSantoDomingo)
CREATE (sacatepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sac_museoPalacioArzobispal)
CREATE (sacatepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sac_ruinasDeCompania)
CREATE (sacatepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sac_catedralSanJose)
CREATE (sacatepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sac_conventoSantaClara)
CREATE (sacatepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sac_conventoCapuchinas)
CREATE (sacatepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sac_iglesiaConventoMerced)
CREATE (sacatepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sac_claustroSanJeronimo)
CREATE (altaVerapaz)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(aver_semucChampey)
CREATE (altaVerapaz)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(aver_lagLachua)
CREATE (altaVerapaz)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(aver_biotopoQuetzal)
CREATE (altaVerapaz)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(aver_grutasLanquin)
CREATE (altaVerapaz)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(aver_hunNalYe)
CREATE (altaVerapaz)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(aver_grutasReyMarcos)
CREATE (altaVerapaz)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(aver_cuevasSetzol)
CREATE (altaVerapaz)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(aver_cuevasBombilPek)
CREATE (altaVerapaz)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(ever_ParqueCentralCoban)
CREATE (altaVerapaz)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(ever_cuevasCandelaria)
CREATE (bajaVerapaz)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(bver_saltoChilasco)
CREATE (bajaVerapaz)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(bver_museoRabinalAchi)
CREATE (bajaVerapaz)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(bver_parroquiaMiguelArcangel)
CREATE (bajaVerapaz)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(bver_museoKomoon)
CREATE (bajaVerapaz)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(bver_cataratasChupadero)
CREATE (bajaVerapaz)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(bver_rioEscondido)
CREATE (bajaVerapaz)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(bver_museoTrapiche)
CREATE (peten)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(pet_lagoItza)
CREATE (cguatemala)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(gt_palacioNacional)
CREATE (cguatemala)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(gt_zooAurora)
CREATE (cguatemala)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(gt_catedralGuatemala)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(peten)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(cguatemala)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(altaVerapaz)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(bajaVerapaz)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(chiquimula)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(elProgreso)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(izabal)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(Zacapa)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(jalapa)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(jutiapa)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(santaRosa)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(chimaltenango)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(escuintla)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(sacatepequez)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(retalhuleu)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(sanMarcos)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(solola)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(suchitepequez)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(totonicapan)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(quetzaltenango)
CREATE (pocoman)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(jalapa)
CREATE (chorti)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(chiquimula)
CREATE (chorti)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(Zacapa)
CREATE (garifuna)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(izabal)
CREATE (quekchi)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(izabal)
CREATE (kaqchikel)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(elProgreso)
CREATE (pocoman)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(elProgreso)
CREATE (kaqchikel)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(sacatepequez)
CREATE (achi)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(altaVerapaz)
CREATE (quekchi)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(altaVerapaz)
CREATE (pocomchi)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(altaVerapaz)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(chi_iximche)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(chi_lagunachicoy)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(chi_casaxaraymolino)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(chi_volcandefuego)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(chi_galeriadeartetzutujil)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(chi_mixcoviejo)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(chi_volcandeacatenango)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(chi_fincacalerachichavac)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(chi_patzun)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_volcantajumulco)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_volcantacana)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_miradorixchel)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_miradorrostromaya)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_nahuala)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(tot_riscosdemomostenango)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(tot_miradorcerropaclom)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(tot_igleasiasanandresxecul)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(tot_mercadosanfranciscoelalto)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(tot_cascadapatrubala)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(tot_parqueecologicochajilsiwan)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(tot_volcancuxliquel)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(tot_sancristobal)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(tot_momostenango)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(tot_sanfranciscoelalto)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(tot_cuevasdesanmiguel)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(tot_aguastermalessanbartolo)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(tot_nueveriscos)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(que_ermitadelaconcepcionsalcaja)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(que_elviejopalmar)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(que_museodelferrocarrildelosaltos)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(QUE_LAGUNAYVOLCANDECHICABAL)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(que_cerroelbaul)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(que_templominerva)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(que_casadelaculturanoj)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(que_volcansantamaria)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(que_museodelahistorianatural)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(que_pasajeenriquez)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(que_lascumbresecosaunas)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(que_museoixkikdeltrajemaya)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(que_teatromunicipal)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(que_volcansantiaguito)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(que_volcancerroquemado)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(que_iglesiasannicolas)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(que_volcanzunil)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(hue_ruinasdezaculeu)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(hue_elcimarron)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(hue_senderoecologicolameceta)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(hue_fincachacula)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(hue_miradordiéguezolaverri)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(hue_unicornioazul)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(hue_elmamut)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(hue_puedracuache)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(aver_semucChampey)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(aver_lagLachua)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(ever_ParqueCentralCoban)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(bver_museoRabinalAchi)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(bver_parroquiaMiguelArcangel)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pet_tikal)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pet_islaFlores)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pet_resBiosferaMaya)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pet_lagunaYaxha)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pet_pNacLagunaTigre)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pet_pNacSierraLacandon)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pet_lagunaPetexbatun)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pet_petencito)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pet_parqueActunKan)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pet_craterAzul)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jut_lagoGuija)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jut_lagunaAtescatempa)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jut_playaMarina)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jut_volcanViboras)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jut_volcanChingo)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jut_volcanIxtepeque)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jut_volcanSuchitan)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jut_volcanMoyuta)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jut_cuevaAndaMira)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jal_cascadaTatasirire)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jal_lagunaAchiotes)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jal_ruinasIngenioAyarza)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jal_iglesiaJilotepeque)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jal_lagunaHoyo)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jal_volcanJumay)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jal_volcanAlzatete)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(chi_basilicaEsquipulas)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(chi_cuevaMinas)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(chi_fincaGirasoles)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(chi_volcanIpala)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(zac_cerroMiramundos)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(zac_museoFerrocarril)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(zac_ValleDorado)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(zac_museoPalenGeolo)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(iz_arqueoQuirigua)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(iz_castilloSanFelipe)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(iz_lagoIzabal)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(iz_playaDorada)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(iz_rioDulce)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(iz_bahiaAmatique)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(iz_puntaPalma)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(iz_playaGraciosa)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(iz_biotopoChacon)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(iz_cayosDiablo)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_laslisas)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_lagunaixpaco)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_monterrico)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_hawaii)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(ret_takalikabaj)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(ret_museoxulik)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(ret_xocomil)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(ret_champerico)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(ret_xetulul)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_tilapa)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(suc_cafechocola)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(suc_chiquistepeque)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pro_sierraMinas)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pro_aguasTermanes)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pro_cerroPino)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pro_parAcuaticoGuastatoya)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(esc_pacaya)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(esc_ceibaPentandra)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(esc_grutasSanPedro)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(esc_ElPenion)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(esc_playaConacaste)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(esc_playaSemillero)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(esc_playaRamaBlanca)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(esc_playaparedon)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(esc_autoSafari)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(esc_parqueCalderas)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(esc_museoCotzumalguapa)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(bver_museoKomoon)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(bver_rioEscondido)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(bver_museoTrapiche)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pet_lagoItza)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_museoPopolVuh)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_museoArqueologia)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_mapaRelieve)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_mercadoCentral)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_museoFerrocarril)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_museoIxchel)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_museoNacionalArte)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_iglesiaCerritoCarmen)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_hipodromoNorte)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_kaminaljuyu)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_jardinBotanico)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_museoHolocausto)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_volcantecuamburro)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_volcancruzquemada)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sac_volcanAgua)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sac_iglesiaJocotenango)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sac_mercadoSanLucas)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sac_mercadoArtesanias)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sac_museoArmas)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sac_museoLibro)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sac_muesoArteColonial)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sac_museSantoDomingo)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sac_museoPalacioArzobispal)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sac_ruinasDeCompania)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sac_catedralSanJose)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sac_conventoSantaClara)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sac_conventoCapuchinas)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sac_iglesiaConventoMerced)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sac_claustroSanJeronimo)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_palacioNacional)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_zooAurora)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_catedralGuatemala)
CREATE (lluvioso)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_parqueregionalmunicipalastillero)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(chi_parqueMontecristo)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_lagunaayarza)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_canaldechiquimulilla)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_cascadasdelosamates)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_lagunaelpino)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_cascadalaconcepcion)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_riolosesclavos)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(ret_reservapatrocinio)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(ret_takalikmayalodge)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_cataratalaigualdad)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_refugiodelquetzal)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_montainbike)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_santacruzlalaguna)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_sanjuanlalaguna)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(so_theyogaforest)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_cafeloco)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_sanperdrolalaguna)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_museolacustre)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_clubvenaca)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_sanantoniopalopo)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_lacasadedonmemo)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_santiagoatitlan)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_reservanaturalatitlan)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_yatchclubatitlan)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_sanmarcoslalaguna)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_santacatarinapalopo)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_cerrotzankujil)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_sanlucastoliman)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_miradordeatitlan)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_catarataensolola)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_volcansanpedro)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(suc_elchorrosdelcarme)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(suc_relojcentenariochocola)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(suc_cerrocabezadeburro)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(suc_fincalasnubes)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(tot_elaprisco)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(que_fuentesgeorginas)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(hue_cenotesdecandelaria)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(hue_lagunamaxbal)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(hue_rioazul)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(hue_lagunabrava)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(hue_rioquisil)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(hue_lagunamagdalena)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(hue_cuevaselresumidero)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(aver_biotopoQuetzal)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(aver_grutasLanquin)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(aver_hunNalYe)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(aver_grutasReyMarcos)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(aver_cuevasSetzol)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(aver_cuevasBombilPek)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(ever_cuevasCandelaria)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(bver_saltoChilasco)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(bver_cataratasChupadero)
CREATE (pet_lagoItza)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (gt_palacioNacional)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (gt_zooAurora)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (gt_catedralGuatemala)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (gt_catedralGuatemala)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(religioso)
CREATE (gt_museoPopolVuh)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (pet_tikal)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(arqueologico)
CREATE (pet_tikal)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (pet_islaFlores)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (pet_islaFlores)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gastronomico)
CREATE (pet_resBiosferaMaya)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (pet_resBiosferaMaya)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (pet_resBiosferaMaya)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(arqueologico)
CREATE (pet_lagunaYaxha)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (pet_pNacLagunaTigre)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (pet_pNacSierraLacandon)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (pet_lagunaPetexbatun)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (pet_petencito)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (pet_petencito)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (pet_parqueActunKan)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (pet_parqueActunKan)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (pet_craterAzul)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (gt_museoArqueologia)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(etnoturismo)
CREATE (gt_museoArqueologia)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (gt_museoArqueologia)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(arqueologico)
CREATE (gt_mapaRelieve)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (gt_mercadoCentral)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (gt_mercadoCentral)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gastronomico)
CREATE (gt_museoIxchel)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(etnoturismo)
CREATE (gt_museoIxchel)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (gt_museoFerrocarril)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (gt_museoNacionalArte)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (gt_iglesiaCerritoCarmen)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (gt_iglesiaCerritoCarmen)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(religioso)
CREATE (gt_hipodromoNorte)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (gt_hipodromoNorte)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(deportivo)
CREATE (gt_kaminaljuyu)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(arqueologico)
CREATE (gt_kaminaljuyu)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (gt_jardinBotanico)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (gt_jardinBotanico)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (gt_museoHolocausto)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (gt_museoHolocausto)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(etnoturismo)
CREATE (jut_lagoGuija)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (jut_lagunaAtescatempa)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (jut_playaMarina)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (jut_volcanViboras)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (jut_volcanViboras)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (jut_volcanChingo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (jut_volcanChingo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (jut_volcanIxtepeque)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (jut_volcanIxtepeque)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (jut_volcanSuchitan)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (jut_volcanSuchitan)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (jut_volcanMoyuta)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (jut_volcanMoyuta)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (jut_cuevaAndaMira)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (jut_cuevaAndaMira)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (jal_cascadaTatasirire)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (jal_cascadaTatasirire)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (jal_lagunaAchiotes)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (jal_ruinasIngenioAyarza)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (jal_iglesiaJilotepeque)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (jal_iglesiaJilotepeque)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(religioso)
CREATE (jal_lagunaHoyo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (jal_volcanJumay)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (jal_volcanJumay)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (jal_volcanAlzatete)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (jal_volcanAlzatete)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (chi_basilicaEsquipulas)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (chi_basilicaEsquipulas)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(religioso)
CREATE (chi_cuevaMinas)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (chi_fincaGirasoles)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (chi_cuevaMinas)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(etnoturismo)
CREATE (chi_volcanIpala)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (chi_volcanIpala)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (chi_parqueMontecristo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (chi_parqueMontecristo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (zac_cerroMiramundos)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (zac_museoFerrocarril)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (zac_ValleDorado)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (zac_museoPalenGeolo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (zac_museoPalenGeolo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (iz_arqueoQuirigua)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(arqueologico)
CREATE (iz_castilloSanFelipe)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (iz_lagoIzabal)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (iz_lagoIzabal)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (jut_lagunaAtescatempa)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (jal_lagunaHoyo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (jal_lagunaAchiotes)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (iz_playaDorada)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (iz_playaDorada)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (iz_rioDulce)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (iz_rioDulce)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (iz_bahiaAmatique)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (iz_puntaPalma)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (iz_puntaPalma)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (iz_playaGraciosa)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (iz_playaGraciosa)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (iz_biotopoChacon)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (iz_biotopoChacon)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (iz_cayosDiablo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (iz_cayosDiablo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (pro_sierraMinas)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (pro_sierraMinas)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (pro_aguasTermanes)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (pro_aguasTermanes)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (pro_cerroPino)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (pro_parAcuaticoGuastatoya)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (esc_pacaya)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (esc_pacaya)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (esc_ceibaPentandra)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(arqueologico)
CREATE (esc_ceibaPentandra)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (esc_grutasSanPedro)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (esc_grutasSanPedro)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (esc_ElPenion)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (esc_ElPenion)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (esc_playaConacaste)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (esc_playaSemillero)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (esc_playaRamaBlanca)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (esc_playaparedon)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (esc_autoSafari)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (esc_parqueCalderas)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (esc_parqueCalderas)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (esc_museoCotzumalguapa)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (sac_volcanAgua)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (sac_volcanAgua)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (sac_iglesiaJocotenango)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(religioso)
CREATE (sac_iglesiaJocotenango)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (sac_mercadoSanLucas)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (sac_mercadoSanLucas)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gastronomico)
CREATE (sac_mercadoArtesanias)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (sac_mercadoArtesanias)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(etnoturismo)
CREATE (sac_museoArmas)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (sac_museoLibro)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (sac_muesoArteColonial)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (sac_museSantoDomingo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (sac_museoPalacioArzobispal)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (sac_ruinasDeCompania)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (sac_catedralSanJose)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (sac_conventoSantaClara)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (sac_conventoSantaClara)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(religioso)
CREATE (sac_catedralSanJose)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(religioso)
CREATE (sac_conventoCapuchinas)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (sac_conventoCapuchinas)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(religioso)
CREATE (sac_iglesiaConventoMerced)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (sac_iglesiaConventoMerced)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(religioso)
CREATE (sac_claustroSanJeronimo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (sac_claustroSanJeronimo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(religioso)
CREATE (aver_semucChampey)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (aver_semucChampey)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (aver_lagLachua)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (aver_lagLachua)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (aver_biotopoQuetzal)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (aver_biotopoQuetzal)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (aver_grutasLanquin)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (aver_grutasLanquin)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (aver_hunNalYe)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (aver_hunNalYe)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (aver_grutasReyMarcos)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (aver_grutasReyMarcos)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (aver_cuevasSetzol)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (aver_cuevasSetzol)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (aver_cuevasBombilPek)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (aver_cuevasBombilPek)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (ever_ParqueCentralCoban)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (ever_cuevasCandelaria)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (ever_cuevasCandelaria)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (bver_museoRabinalAchi)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (bver_parroquiaMiguelArcangel)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(religioso)
CREATE (bver_parroquiaMiguelArcangel)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (bver_museoKomoon)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (bver_cataratasChupadero)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (bver_cataratasChupadero)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)
CREATE (bver_rioEscondido)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aventura)
CREATE (bver_rioEscondido)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ecoturismo)
CREATE (bver_museoTrapiche)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(cultural)