

CREATE (GTM:Pais {Nombre: 'Guatemala'})
CREATE (rpeten:Region {Nombre: 'Peten'})
CREATE (metropolitana:Region {Nombre: 'Metropolitana'})
CREATE (norte:Region {Nombre: 'Norte'})
CREATE (nororiente:Region {Nombre: 'Nororiente'})
CREATE (suroriente:Region {Nombre: 'Suroriente'})
CREATE (central:Region {Nombre: 'Central'})
CREATE (suroccidente:Region {Nombre: 'Suroccidente'})
CREATE (noroccidente:Region {Nombre: 'Noroccidente'})
CREATE (peten:Municipio {titulo: 'Peten'})
CREATE (cguatemala:Municipio {titulo: 'Ciudad de Guatemala'})
CREATE (altaVerapaz:Municipio {titulo: 'Alta Verapaz'})
CREATE (bajaVerapaz:Municipio {titulo: 'Baja Verapaz'})
CREATE (chiquimula:Municipio {titulo: 'Chiquimula'})
CREATE (elProgreso:Municipio {titulo: 'El Progreso'})
CREATE (izabal:Municipio {titulo: 'Izabal'})
CREATE (Zacapa:Municipio {titulo: 'Zacapa'})
CREATE (jalapa:Municipio {titulo: 'Jalapa'})
CREATE (jutiapa:Municipio {titulo: 'Jutiapa'})
CREATE (santaRosa:Municipio {titulo: 'Santa Rosa'})
CREATE (chimaltenango:Municipio {titulo: 'Chimaltenango'})
CREATE (escuintla:Municipio {titulo: 'Escuintla'})
CREATE (sacatepequez:Municipio {titulo: 'Sacatepequez'})
CREATE (retalhuleu:Municipio {titulo: 'Retalhuleu'})
CREATE (sanMarcos:Municipio {titulo: 'San Marcos'})
CREATE (solola:Municipio {titulo: 'Solola'})
CREATE (suchitepequez:Municipio {titulo: 'Suchitepequez'})
CREATE (totonicapan:Municipio {titulo: 'Totonicapan'})
CREATE (quetzaltenango:Municipio {titulo: 'Quetzaltenango'})
CREATE (Huehue:Municipio {titulo: 'Huehuetenango'})
CREATE (frio:Clima {titulo: 'Frio'})
CREATE (calido:Clima {titulo: 'Calido'})
CREATE (templado:Clima {titulo: 'Templado'})
CREATE (lluvioso:Clima {titulo: 'Lluvioso'})
CREATE (humedo:Clima {titulo: 'Humedo'})
CREATE (gt_museoPopolVuh:Turismo {Lugar: 'Museo Popol Vuh'})
CREATE (pet_tikal:Turismo {Lugar: 'Tikal'})
CREATE (pet_islaFlores:Turismo {Lugar: 'Isla de Flores'})
CREATE (pet_resBiosferaMaya:Turismo {Lugar: 'Reserva de la Biosfera Maya'})
CREATE (pet_lagunaYaxha:Turismo {Lugar: 'Laguna Yaxha'})
CREATE (pet_pNacLagunaTigre:Turismo {Lugar: 'Parque Nacional Laguna del Tigre'})
CREATE (pet_pNacSierraLacandon:Turismo {Lugar: 'Parque Nacional Sierra del Lacandon'})
CREATE (pet_lagunaPetexbatun:Turismo {Lugar: 'Laguna Petexbatun'})
CREATE (pet_petencito:Turismo {Lugar: 'Petencito'})
CREATE (pet_parqueActunKan:Turismo {Lugar: 'Parque Regional Actun Kan'})
CREATE (pet_craterAzul:Turismo {Lugar: 'Crater Azul'})
CREATE (gt_museoArqueologia:Turismo {Lugar: 'Museo Nacional de Arqueologia y Etnologia de Guatemala'})
CREATE (gt_mapaRelieve:Turismo {Lugar: 'Mapa en Relieve de Guatemala'})
CREATE (gt_mercadoCentral:Turismo {Lugar: 'Mercado Central'})
CREATE (gt_museoFerrocarril:Turismo {Lugar: 'Museo del Ferrocarril de Guatemala'})
CREATE (gt_museoIxchel:Turismo {Lugar: 'Museo Ixchel del Traje Indigena'})
CREATE (gt_museoNacionalArte:Turismo {Lugar: 'Museo Nacional de Arte Moderno Carlos Merida'})
CREATE (gt_iglesiaCerritoCarmen:Turismo {Lugar: 'Iglesia del Cerrito del Carmen'})
CREATE (gt_hipodromoNorte:Turismo {Lugar: 'Hipodromo del Norte'})
CREATE (gt_kaminaljuyu:Turismo {Lugar: 'Zona Arqueologica Kaminaljuyu'})
CREATE (gt_jardinBotanico:Turismo {Lugar: 'Jardin Botanico de Guatemala'})
CREATE (gt_museoHolocausto:Turismo {Lugar: 'Museo del Holocausto Guatemala'})
CREATE (jut_lagoGuija:Turismo {Lugar: 'Lago de Guija'})
CREATE (jut_lagunaAtescatempa:Turismo {Lugar: 'Laguna Atescatempa'})
CREATE (jut_playaMarina:Turismo {Lugar: 'Playas Marinas'})
CREATE (jut_volcanViboras:Turismo {Lugar: 'Volcan de las Viboras'})
CREATE (jut_volcanChingo:Turismo {Lugar: 'Volcan Chingo'})
CREATE (jut_volcanIxtepeque:Turismo {Lugar: 'Volcan Ixtepeque'})
CREATE (jut_volcanSuchitan:Turismo {Lugar: 'Volcan Suchitan'})
CREATE (jut_volcanMoyuta:Turismo {Lugar: 'Volcan Moyuta'})
CREATE (jut_cuevaAndaMira:Turismo {Lugar: 'Cueva de Anda Mira'})
CREATE (jal_cascadaTatasirire:Turismo {Lugar: 'Cascadas de Tatasirire'})
CREATE (jal_lagunaAchiotes:Turismo {Lugar: 'Laguna de Achiotes Jumay'})
CREATE (jal_ruinasIngenioAyarza:Turismo {Lugar: 'Ruinas Coloniales del Ingenio Ayarza'})
CREATE (jal_iglesiaJilotepeque:Turismo {Lugar: 'Iglesia Colonial de San Luis Jilotepeque'})
CREATE (jal_lagunaHoyo:Turismo {Lugar: 'Laguna del Hoyo'})
CREATE (jal_volcanJumay:Turismo {Lugar: 'Volcan Jumay'})
CREATE (jal_volcanAlzatete:Turismo {Lugar: 'Volcan Alzatete'})
CREATE (chi_basilicaEsquipulas:Turismo {Lugar: 'Basilica de Esquipulas'})
CREATE (chi_cuevaMinas:Turismo {Lugar: 'La cueva de las Minas'})
CREATE (chi_fincaGirasoles:Turismo {Lugar: 'Finca Los Girasoles'})
CREATE (chi_volcanIpala:Turismo {Lugar: 'Volcan de Ipala'})
CREATE (chi_parqueMontecristo:Turismo {Lugar: 'Parque Nacional Montecristo o Trifinio'})
CREATE (zac_cerroMiramundos:Turismo {Lugar: 'Cerro Miramundo'})
CREATE (zac_museoFerrocarril:Turismo {Lugar: 'Museo del Ferrocarril Zacapa'})
CREATE (zac_ValleDorado:Turismo {Lugar: 'Turicentro Valle Dorado'})
CREATE (zac_museoPalenGeolo:Turismo {Lugar: 'Museo de Paleontologia, Arqueologia y Geologia'})
CREATE (iz_arqueoQuirigua:Turismo {Lugar: 'Sitio Arqueologico de Quirigua'})
CREATE (iz_castilloSanFelipe:Turismo {Lugar: 'Castillo de San Felipe de Lara'})
CREATE (iz_lagoIzabal:Turismo {Lugar: 'Lago de Izabal'})
CREATE (iz_playaDorada:Turismo {Lugar: 'Playa Dorada'})
CREATE (iz_rioDulce:Turismo {Lugar: 'Rio Dulce'})
CREATE (iz_bahiaAmatique:Turismo {Lugar: 'Bahia de Amatique'})
CREATE (iz_puntaPalma:Turismo {Lugar: 'Punta de Palma'})
CREATE (iz_playaGraciosa:Turismo {Lugar: 'Playa La Graciosa'})
CREATE (iz_biotopoChacon:Turismo {Lugar: 'Biotopo Protegido Chacon Machacas'})
CREATE (iz_cayosDiablo:Turismo {Lugar: 'Los Cayos del Diablo'})
CREATE (san_lagunaayarza:Turismo {Lugar: 'Laguna de Ayarza'})
CREATE (san_laslisas:Turismo {Lugar: 'Playa Las Lisas'})
CREATE (san_lagunaixpaco:Turismo {Lugar: 'Laguna Ixpaco'})
CREATE (san_monterrico:Turismo {Lugar: 'Playa Monterrico'})
CREATE (san_canaldechiquimulilla:Turismo {Lugar: 'Canal De Chiquimulilla'})
CREATE (san_cascadasdelosamates:Turismo {Lugar: 'Cascadas de los Amates'})
CREATE (san_hawaii:Turismo {Lugar: 'Playa El Hawaii'})
CREATE (san_lagunaelpino:Turismo {Lugar: 'Laguna El Pino'})
CREATE (san_volcantecuamburro:Turismo {Lugar: 'Volcan Tecuamburro'})
CREATE (san_cascadalaconcepcion:Turismo {Lugar: 'Cascada La Concepcion'})
CREATE (san_volcancruzquemada:Turismo {Lugar: 'Volcan Cruz Quemada'})
CREATE (san_riolosesclavos:Turismo {Lugar: 'Rio Los Esclavos'})
CREATE (chi_iximche:Turismo {Lugar: 'Iximche'})
CREATE (chi_lagunachicoy:Turismo {Lugar: 'Laguna Chichoy'})
CREATE (chi_casaxaraymolino:Turismo {Lugar: 'Casa Xara y Molino'})
CREATE (chi_volcandefuego:Turismo {Lugar: 'Volcan de Fuego'})
CREATE (chi_galeriadeartetzutujil:Turismo {Lugar: 'Galeria de Arte Txutujil'})
CREATE (chi_mixcoviejo:Turismo {Lugar: 'Mixco Viejo'})
CREATE (chi_volcandeacatenango:Turismo {Lugar: 'Volcan de Acatenango'})
CREATE (chi_fincacalerachichavac:Turismo {Lugar: 'Finca Caleras Chichavac'})
CREATE (chi_patzun:Turismo {Lugar: 'Patzun'})
CREATE (ret_takalikabaj:Turismo {Lugar: 'Takalik Abaj'})
CREATE (ret_museoxulik:Turismo {Lugar: 'Museo Xulik'})
CREATE (ret_reservapatrocinio:Turismo {Lugar: 'Reserva Patrocinio'})
CREATE (ret_xocomil:Turismo {Lugar: 'Xocomil'})
CREATE (ret_champerico:Turismo {Lugar: 'Playa de Champerico'})
CREATE (ret_takalikmayalodge:Turismo {Lugar: 'Takalik Maya Lodge'})
CREATE (ret_xetulul:Turismo {Lugar: 'Xetulul'})
CREATE (san_cataratalaigualdad:Turismo {Lugar: 'Catarata La Igualdad'})
CREATE (san_parqueregionalmunicipalastillero:Turismo {Lugar: 'Parque Regional Municipal Astillero'})
CREATE (san_refugiodelquetzal:Turismo {Lugar: 'Refugio del Quetzal'})
CREATE (san_volcantajumulco:Turismo {Lugar: 'Volcan Tajumulco'})
CREATE (san_montainbike:Turismo {Lugar: 'Mountain Bike'})
CREATE (san_tilapa:Turismo {Lugar: 'Playas de Tilapa'})
CREATE (san_volcantacana:Turismo {Lugar: 'Volcan Tacana'})
CREATE (sol_miradorixchel:Turismo {Lugar: 'Mirador Ixchel'})
CREATE (sol_santacruzlalaguna:Turismo {Lugar: 'Santa Cruz La Laguna'})
CREATE (sol_sanjuanlalaguna:Turismo {Lugar: 'San Juan La Laguna'})
CREATE (so_theyogaforest:Turismo {Lugar: 'The Yogo Forest'})
CREATE (sol_cafeloco:Turismo {Lugar: 'Cafe Loco'})
CREATE (sol_miradorrostromaya:Turismo {Lugar: 'Mirador Rostro Maya'})
CREATE (sol_sanperdrolalaguna:Turismo {Lugar: 'San Pedro La Laguna'})
CREATE (sol_museolacustre:Turismo {Lugar: 'Museo Lacustre'})
CREATE (sol_clubvenaca:Turismo {Lugar: 'Club Ven Aca'})
CREATE (sol_sanantoniopalopo:Turismo {Lugar: 'San Antonio Palopo'})
CREATE (sol_lacasadedonmemo:Turismo {Lugar: 'La Casa De Don Memo'})
CREATE (sol_santiagoatitlan:Turismo {Lugar: 'Santiago Atitlan'})
CREATE (sol_reservanaturalatitlan:Turismo {Lugar: 'Reserva Natural Atitlan'})
CREATE (sol_yatchclubatitlan:Turismo {Lugar: 'Yatch Club Atitlan'})
CREATE (sol_sanmarcoslalaguna:Turismo {Lugar: 'San Marcos La Laguna'})
CREATE (sol_santacatarinapalopo:Turismo {Lugar: 'Santa Catarina Palopo'})
CREATE (sol_cerrotzankujil:Turismo {Lugar: 'Cerro Tzankujil'})
CREATE (sol_sanlucastoliman:Turismo {Lugar: 'San Lucas Toliman'})
CREATE (sol_miradordeatitlan:Turismo {Lugar: 'Mirador de Atitlan'})
CREATE (sol_catarataensolola:Turismo {Lugar: 'Catarata en Solola'})
CREATE (sol_volcansanpedro:Turismo {Lugar: 'Parque Ecologico Volcan San Pedro'})
CREATE (sol_nahuala:Turismo {Lugar: 'Nahuala'})
CREATE (suc_cafechocola:Turismo {Lugar: 'Beneficio de cafe Chocola'})
CREATE (suc_elchorrosdelcarme:Turismo {Lugar: 'El Chorros del Carmen'})
CREATE (suc_relojcentenariochocola:Turismo {Lugar: 'Reloj Centenario Chocola'})
CREATE (suc_cerrocabezadeburro:Turismo {Lugar: 'Cerro Cabeza de Burro'})
CREATE (suc_chiquistepeque:Turismo {Lugar: 'Playa de Chiquistepeque'})
CREATE (suc_fincalasnubes:Turismo {Lugar: 'Finca Las Nubes'})
CREATE (tot_elaprisco:Turismo {Lugar: 'Sendero Ecologico El Aprisco'})
CREATE (tot_riscosdemomostenango:Turismo {Lugar: 'Riscos de Momostenango'})
CREATE (tot_miradorcerropaclom:Turismo {Lugar: 'Mirador Cerro Paclom'})
CREATE (tot_igleasiasanandresxecul:Turismo {Lugar: 'Iglesia San Andres Xecul'})
CREATE (tot_mercadosanfranciscoelalto:Turismo {Lugar: 'Mercado San Francisco El Alto'})
CREATE (tot_cascadapatrubala:Turismo {Lugar: 'Cascada Patrubala'})
CREATE (tot_parqueecologicochajilsiwan:Turismo {Lugar: 'Parque Ecologico Chajil Siwan'})
CREATE (tot_volcancuxliquel:Turismo {Lugar: 'Volcan Cuxliquel'})
CREATE (tot_sancristobal:Turismo {Lugar: 'San Cristobal'})
CREATE (tot_momostenango:Turismo {Lugar: 'Momostenango,'})
CREATE (tot_sanfranciscoelalto:Turismo {Lugar: 'San Francisco El Alto'})
CREATE (tot_cuevasdesanmiguel:Turismo {Lugar: 'Cuevas de San Miguel'})
CREATE (tot_aguastermalessanbartolo:Turismo {Lugar: 'Aguas termales San Bartolo'})
CREATE (tot_nueveriscos:Turismo {Lugar: 'Nueve Sillas'})
CREATE (que_fuentesgeorginas:Turismo {Lugar: 'Fuentes Georginas'})
CREATE (que_ermitadelaconcepcionsalcaja:Turismo {Lugar: 'Ermita de la Concepcion Salcaja'})
CREATE (que_elviejopalmar:Turismo {Lugar: 'El Viejo Palmar'})
CREATE (que_museodelferrocarrildelosaltos:Turismo {Lugar: 'Museo del Ferrocarril de los Altos'})
CREATE (QUE_LAGUNAYVOLCANDECHICABAL:Turismo {Lugar: 'Laguna y volcan de Chicabal'})
CREATE (que_cerroelbaul:Turismo {Lugar: 'Cerro El Baul'})
CREATE (que_templominerva:Turismo {Lugar: 'Templo Minerva'})
CREATE (que_casadelaculturanoj:Turismo {Lugar: 'Casa de la Cultura Noj'})
CREATE (que_volcansantamaria:Turismo {Lugar: 'Volcan Santa Maria'})
CREATE (que_museodelahistorianatural:Turismo {Lugar: 'Museo de Historia Natural'})
CREATE (que_pasajeenriquez:Turismo {Lugar: 'Pasaje Enriquez'})
CREATE (que_lascumbresecosaunas:Turismo {Lugar: 'Las Cumbres Eco Saunas'})
CREATE (que_museoixkikdeltrajemaya:Turismo {Lugar: 'Museo Ixkik del Traje Maya'})
CREATE (que_teatromunicipal:Turismo {Lugar: 'Teatro Municipal'})
CREATE (que_volcansantiaguito:Turismo {Lugar: 'Volcan Santiaguito'})
CREATE (que_volcancerroquemado:Turismo {Lugar: 'Volcan Cerro Quemado'})
CREATE (que_iglesiasannicolas:Turismo {Lugar: 'Iglesia San Nicolas'})
CREATE (que_volcanzunil:Turismo {Lugar: 'Volcan Zunil'})
CREATE (hue_cenotesdecandelaria:Turismo {Lugar: 'Cenotes de Candelaria'})
CREATE (hue_lagunamaxbal:Turismo {Lugar: 'Laguna Maxbal'})
CREATE (hue_rioazul:Turismo {Lugar: 'Rio Azul'})
CREATE (hue_lagunabrava:Turismo {Lugar: 'Laguna Brava'})
CREATE (hue_ruinasdezaculeu:Turismo {Lugar: 'Ruinas de Zaculeu'})
CREATE (hue_elcimarron:Turismo {Lugar: 'El Cimarron'})
CREATE (hue_senderoecologicolameceta:Turismo {Lugar: 'Sendero Ecologico La Maceta'})
CREATE (hue_rioquisil:Turismo {Lugar: 'Rio Quisil'})
CREATE (hue_fincachacula:Turismo {Lugar: 'Posada Rural Finca Chacula'})
CREATE (hue_lagunamagdalena:Turismo {Lugar: 'Laguna Magdalena'})
CREATE (hue_miradordieguezolaverri:Turismo {Lugar: 'Mirador Dieguez Olaverri'})
CREATE (hue_unicornioazul:Turismo {Lugar: 'Posada Rural y Ecuestre Unicornio Azul'})
CREATE (hue_elmamut:Turismo {Lugar: 'El Mamut'})
CREATE (hue_puedracuache:Turismo {Lugar: 'La Piedra Cuache'})
CREATE (hue_cuevaselresumidero:Turismo {Lugar: 'Cuevas El Resumidero'})
CREATE (pro_sierraMinas:Turismo {Lugar: 'La Sierra de las Minas'})
CREATE (pro_aguasTermanes:Turismo {Lugar: 'Aguas Termales del Rio Los Platanos'})
CREATE (pro_cerroPino:Turismo {Lugar: 'Cerro del Pino'})
CREATE (pro_parAcuaticoGuastatoya:Turismo {Lugar: 'Parque Acuatico Guastatoya'})
CREATE (esc_pacaya:Turismo {Lugar: 'Volcan de Pacaya'})
CREATE (esc_ceibaPentandra:Turismo {Lugar: 'Ceiba Pentandra'})
CREATE (esc_grutasSanPedro:Turismo {Lugar: 'Grutas San Pedro Martir'})
CREATE (esc_ElPenion:Turismo {Lugar: 'El Peñon'})
CREATE (esc_playaConacaste:Turismo {Lugar: 'Playa El Conacaste'})
CREATE (esc_playaSemillero:Turismo {Lugar: 'Playa El Semillero'})
CREATE (esc_playaRamaBlanca:Turismo {Lugar: 'Playa San Jose Rama Blanca'})
CREATE (esc_playaparedon:Turismo {Lugar: 'Playa el Paredon'})
CREATE (esc_autoSafari:Turismo {Lugar: 'Auto Safari Chapin'})
CREATE (esc_parqueCalderas:Turismo {Lugar: 'Parque Nacional Calderas'})
CREATE (esc_museoCotzumalguapa:Turismo {Lugar: 'Museo Cultural Cotzumalguapa'})
CREATE (sac_volcanAgua:Turismo {Lugar: 'Volcan de Agua'})
CREATE (sac_iglesiaJocotenango:Turismo {Lugar: 'Iglesia de Jocotenango'})
CREATE (sac_mercadoSanLucas:Turismo {Lugar: 'Mercado de San Lucas'})
CREATE (sac_mercadoArtesanias:Turismo {Lugar: 'Mercado de Artesanias'})
CREATE (sac_museoArmas:Turismo {Lugar: 'Museo De Santiago de Los Caballeros'})
CREATE (sac_museoLibro:Turismo {Lugar: 'Museo del Libro Antiguo'})
CREATE (sac_muesoArteColonial:Turismo {Lugar: 'Museo de Arte Colonial'})
CREATE (sac_museSantoDomingo:Turismo {Lugar: 'Museo Casa Santo Domingo'})
CREATE (sac_museoPalacioArzobispal:Turismo {Lugar: 'Museo Del Palacio Arzobispal, San Juan El Obispo'})
CREATE (sac_ruinasDeCompania:Turismo {Lugar: 'Ruinas de la Compañia de Jesus'})
CREATE (sac_catedralSanJose:Turismo {Lugar: 'Catedral San Jose'})
CREATE (sac_conventoSantaClara:Turismo {Lugar: 'Convento de Santa Clara'})
CREATE (sac_conventoCapuchinas:Turismo {Lugar: 'Convento de Capuchinas'})
CREATE (sac_iglesiaConventoMerced:Turismo {Lugar: 'Iglesia y Convento de la Merced'})
CREATE (sac_claustroSanJeronimo:Turismo {Lugar: 'Claustro de San Jeronimo'})
CREATE (aver_semucChampey:Turismo {Lugar: 'Semuc Champey'})
CREATE (aver_lagLachua:Turismo {Lugar: 'Laguna Lachua'})
CREATE (aver_biotopoQuetzal:Turismo {Lugar: 'Biotopo del Quetzal'})
CREATE (aver_grutasLanquin:Turismo {Lugar: 'Parque Nacional Grutas de Lanquin'})
CREATE (aver_hunNalYe:Turismo {Lugar: 'Hun Nal Ye'})
CREATE (aver_grutasReyMarcos:Turismo {Lugar: 'Grutas del Rey Marcos'})
CREATE (aver_cuevasSetzol:Turismo {Lugar: 'Cuevas De Setzol'})
CREATE (aver_cuevasBombilPek:Turismo {Lugar: 'Cuevas de Bombil Pek'})
CREATE (ever_ParqueCentralCoban:Turismo {Lugar: 'Parque Central Coban'})
CREATE (ever_cuevasCandelaria:Turismo {Lugar: 'Cuevas de Candelaria Mucbiha'})
CREATE (bver_saltoChilasco:Turismo {Lugar: 'Salto de Chilasco'})
CREATE (bver_museoRabinalAchi:Turismo {Lugar: 'Museo Comunitario Rabinal Achi'})
CREATE (bver_parroquiaMiguelArcangel:Turismo {Lugar: 'Parroquia San Miguel Arcangel'})
CREATE (bver_museoKomoon:Turismo {Lugar: 'Sitio Arqueologico Museo Komoon'})
CREATE (bver_cataratasChupadero:Turismo {Lugar: 'Cataratas El Chupadero'})
CREATE (bver_rioEscondido:Turismo {Lugar: 'Rio Escondido'})
CREATE (bver_museoTrapiche:Turismo {Lugar: 'Museo Regional del Trapiche'})
CREATE (pet_lagoItza:Turismo {Lugar: 'Lago Peten Itza'})
CREATE (gt_palacioNacional:Turismo {Lugar: 'Palacio Nacional de la Cultura'})
CREATE (gt_zooAurora:Turismo {Lugar: 'Zoologico La Aurora'})
CREATE (gt_catedralGuatemala:Turismo {Lugar: 'Catedral de Ciudad de Guatemala'})
CREATE (qeqchi:Idioma {titulo: 'Qeqchi'})
CREATE (pocomchi:Idioma {titulo: 'Pocomchi'})
CREATE (achi:Idioma {titulo: 'Achi'})
CREATE (kiche:Idioma {titulo: 'Kiche'})
CREATE (espaniol:Idioma {titulo: 'Español'})
CREATE (kaqchikel:Idioma {titulo: 'Kaqchikel'})
CREATE (pocoman:Idioma {titulo: 'Pocoman'})
CREATE (chorti:Idioma {titulo: 'Chorti'})
CREATE (garifuna:Idioma {titulo: 'Garifuna'})
CREATE (quekchi:Idioma {titulo: 'Quekchi'})
CREATE (mam:Idioma {titulo: 'Mam'})
CREATE (tzutujil:Idioma {titulo: 'Tzutujil'})
CREATE (ecoturismo:Tipo_Turismo {titulo: 'Ecoturismo'})
CREATE (comunitario:Tipo_Turismo {titulo: 'Comunitario'})
CREATE (cultural:Tipo_Turismo {titulo: 'Cultural'})
CREATE (gastronomico:Tipo_Turismo {titulo: 'Gastronomico'})
CREATE (agroturismo:Tipo_Turismo {titulo: 'Agroturismo'})
CREATE (aventura:Tipo_Turismo {titulo: 'Aventura'})
CREATE (deportivo:Tipo_Turismo {titulo: 'Deportivo'})
CREATE (etnoturismo:Tipo_Turismo {titulo: 'Etnoturismo'})
CREATE (religioso:Tipo_Turismo {titulo: 'Religioso'})
CREATE (arqueologico:Tipo_Turismo {titulo: 'Arqueologico'})


CREATE (rpeten)-[:REGION_PAIS {roles:['Region Pais']}]->(GTM)
CREATE (metropolitana)-[:REGION_PAIS {roles:['Region Pais']}]->(GTM)
CREATE (norte)-[:REGION_PAIS {roles:['Region Pais']}]->(GTM)
CREATE (nororiente)-[:REGION_PAIS {roles:['Region Pais']}]->(GTM)
CREATE (suroriente)-[:REGION_PAIS {roles:['Region Pais']}]->(GTM)
CREATE (central)-[:REGION_PAIS {roles:['Region Pais']}]->(GTM)
CREATE (suroccidente)-[:REGION_PAIS {roles:['Region Pais']}]->(GTM)
CREATE (noroccidente)-[:REGION_PAIS {roles:['Region Pais']}]->(GTM)
CREATE (rpeten)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(peten)
CREATE (metropolitana)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(cguatemala)
CREATE (norte)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(altaVerapaz)
CREATE (norte)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(bajaVerapaz)
CREATE (nororiente)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(chiquimula)
CREATE (nororiente)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(elProgreso)
CREATE (nororiente)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(izabal)
CREATE (nororiente)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(Zacapa)
CREATE (suroriente)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(jalapa)
CREATE (suroriente)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(jutiapa)
CREATE (suroriente)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(santaRosa)
CREATE (central)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(chimaltenango)
CREATE (central)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(escuintla)
CREATE (central)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(sacatepequez)
CREATE (suroccidente)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(retalhuleu)
CREATE (suroccidente)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(sanMarcos)
CREATE (suroccidente)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(solola)
CREATE (suroccidente)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(suchitepequez)
CREATE (suroccidente)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(totonicapan)
CREATE (suroccidente)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(quetzaltenango)
CREATE (noroccidente)-[:MUNICIPIO_REGION {roles:['Municipio Region']}]->(Huehue)
CREATE (cguatemala)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(gt_museoPopolVuh)
CREATE (peten)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(pet_tikal)
CREATE (peten)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(pet_islaFlores)
CREATE (peten)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(pet_resBiosferaMaya)
CREATE (peten)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(pet_lagunaYaxha)
CREATE (peten)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(pet_pNacLagunaTigre)
CREATE (peten)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(pet_pNacSierraLacandon)
CREATE (peten)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(pet_lagunaPetexbatun)
CREATE (peten)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(pet_petencito)
CREATE (peten)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(pet_parqueActunKan)
CREATE (peten)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(pet_craterAzul)
CREATE (cguatemala)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(gt_museoArqueologia)
CREATE (cguatemala)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(gt_mapaRelieve)
CREATE (cguatemala)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(gt_mercadoCentral)
CREATE (cguatemala)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(gt_museoFerrocarril)
CREATE (cguatemala)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(gt_museoIxchel)
CREATE (cguatemala)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(gt_museoNacionalArte)
CREATE (cguatemala)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(gt_iglesiaCerritoCarmen)
CREATE (cguatemala)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(gt_hipodromoNorte)
CREATE (cguatemala)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(gt_kaminaljuyu)
CREATE (cguatemala)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(gt_jardinBotanico)
CREATE (cguatemala)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(gt_museoHolocausto)
CREATE (jutiapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jut_lagoGuija)
CREATE (jutiapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jut_lagunaAtescatempa)
CREATE (jutiapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jut_playaMarina)
CREATE (jutiapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jut_volcanViboras)
CREATE (jutiapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jut_volcanChingo)
CREATE (jutiapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jut_volcanIxtepeque)
CREATE (jutiapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jut_volcanSuchitan)
CREATE (jutiapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jut_volcanMoyuta)
CREATE (jutiapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jut_cuevaAndaMira)
CREATE (jalapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jal_cascadaTatasirire)
CREATE (jalapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jal_lagunaAchiotes)
CREATE (jalapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jal_ruinasIngenioAyarza)
CREATE (jalapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jal_iglesiaJilotepeque)
CREATE (jalapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jal_lagunaHoyo)
CREATE (jalapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jal_volcanJumay)
CREATE (jalapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(jal_volcanAlzatete)
CREATE (chiquimula)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(chi_basilicaEsquipulas)
CREATE (chiquimula)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(chi_cuevaMinas)
CREATE (chiquimula)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(chi_fincaGirasoles)
CREATE (chiquimula)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(chi_volcanIpala)
CREATE (chiquimula)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(chi_parqueMontecristo)
CREATE (Zacapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(zac_cerroMiramundos)
CREATE (Zacapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(zac_museoFerrocarril)
CREATE (Zacapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(zac_ValleDorado)
CREATE (Zacapa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(zac_museoPalenGeolo)
CREATE (izabal)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(iz_arqueoQuirigua)
CREATE (izabal)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(iz_castilloSanFelipe)
CREATE (izabal)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(iz_lagoIzabal)
CREATE (izabal)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(iz_playaDorada)
CREATE (izabal)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(iz_rioDulce)
CREATE (izabal)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(iz_bahiaAmatique)
CREATE (izabal)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(iz_puntaPalma)
CREATE (izabal)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(iz_playaGraciosa)
CREATE (izabal)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(iz_biotopoChacon)
CREATE (izabal)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(iz_cayosDiablo)
CREATE (santaRosa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_lagunaayarza)
CREATE (santaRosa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_laslisas)
CREATE (santaRosa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_lagunaixpaco)
CREATE (santaRosa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_monterrico)
CREATE (santaRosa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_canaldechiquimulilla)
CREATE (santaRosa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_cascadasdelosamates)
CREATE (santaRosa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_hawaii)
CREATE (santaRosa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_lagunaelpino)
CREATE (santaRosa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_volcantecuamburro)
CREATE (santaRosa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_cascadalaconcepcion)
CREATE (santaRosa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_volcancruzquemada)
CREATE (santaRosa)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_riolosesclavos)
CREATE (chimaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(chi_iximche)
CREATE (chimaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(chi_lagunachicoy)
CREATE (chimaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(chi_casaxaraymolino)
CREATE (chimaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(chi_volcandefuego)
CREATE (chimaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(chi_galeriadeartetzutujil)
CREATE (chimaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(chi_mixcoviejo)
CREATE (chimaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(chi_volcandeacatenango)
CREATE (chimaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(chi_fincacalerachichavac)
CREATE (chimaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(chi_patzun)
CREATE (retalhuleu)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(ret_takalikabaj)
CREATE (retalhuleu)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(ret_museoxulik)
CREATE (retalhuleu)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(ret_reservapatrocinio)
CREATE (retalhuleu)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(ret_xocomil)
CREATE (retalhuleu)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(ret_champerico)
CREATE (retalhuleu)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(ret_takalikmayalodge)
CREATE (retalhuleu)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(ret_xetulul)
CREATE (sanMarcos)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_cataratalaigualdad)
CREATE (sanMarcos)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_parqueregionalmunicipalastillero)
CREATE (sanMarcos)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_refugiodelquetzal)
CREATE (sanMarcos)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_volcantajumulco)
CREATE (sanMarcos)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_montainbike)
CREATE (sanMarcos)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_tilapa)
CREATE (sanMarcos)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(san_volcantacana)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_miradorixchel)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_santacruzlalaguna)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_sanjuanlalaguna)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(so_theyogaforest)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_cafeloco)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_miradorrostromaya)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_sanperdrolalaguna)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_museolacustre)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_clubvenaca)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_sanantoniopalopo)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_lacasadedonmemo)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_santiagoatitlan)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_reservanaturalatitlan)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_yatchclubatitlan)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_sanmarcoslalaguna)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_santacatarinapalopo)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_cerrotzankujil)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_sanlucastoliman)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_miradordeatitlan)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_catarataensolola)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_volcansanpedro)
CREATE (solola)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sol_nahuala)
CREATE (suchitepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(suc_cafechocola)
CREATE (suchitepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(suc_elchorrosdelcarme)
CREATE (suchitepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(suc_relojcentenariochocola)
CREATE (suchitepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(suc_cerrocabezadeburro)
CREATE (suchitepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(suc_chiquistepeque)
CREATE (suchitepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(suc_fincalasnubes)
CREATE (totonicapan)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(tot_elaprisco)
CREATE (totonicapan)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(tot_riscosdemomostenango)
CREATE (totonicapan)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(tot_miradorcerropaclom)
CREATE (totonicapan)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(tot_igleasiasanandresxecul)
CREATE (totonicapan)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(tot_mercadosanfranciscoelalto)
CREATE (totonicapan)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(tot_cascadapatrubala)
CREATE (totonicapan)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(tot_parqueecologicochajilsiwan)
CREATE (totonicapan)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(tot_volcancuxliquel)
CREATE (totonicapan)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(tot_sancristobal)
CREATE (totonicapan)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(tot_momostenango)
CREATE (totonicapan)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(tot_sanfranciscoelalto)
CREATE (totonicapan)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(tot_cuevasdesanmiguel)
CREATE (totonicapan)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(tot_aguastermalessanbartolo)
CREATE (totonicapan)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(tot_nueveriscos)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(que_fuentesgeorginas)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(que_ermitadelaconcepcionsalcaja)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(que_elviejopalmar)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(que_museodelferrocarrildelosaltos)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(QUE_LAGUNAYVOLCANDECHICABAL)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(que_cerroelbaul)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(que_templominerva)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(que_casadelaculturanoj)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(que_volcansantamaria)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(que_museodelahistorianatural)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(que_pasajeenriquez)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(que_lascumbresecosaunas)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(que_museoixkikdeltrajemaya)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(que_teatromunicipal)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(que_volcansantiaguito)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(que_volcancerroquemado)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(que_iglesiasannicolas)
CREATE (quetzaltenango)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(que_volcanzunil)
CREATE (Huehue)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(hue_cenotesdecandelaria)
CREATE (Huehue)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(hue_lagunamaxbal)
CREATE (Huehue)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(hue_rioazul)
CREATE (Huehue)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(hue_lagunabrava)
CREATE (Huehue)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(hue_ruinasdezaculeu)
CREATE (Huehue)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(hue_elcimarron)
CREATE (Huehue)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(hue_senderoecologicolameceta)
CREATE (Huehue)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(hue_rioquisil)
CREATE (Huehue)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(hue_fincachacula)
CREATE (Huehue)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(hue_lagunamagdalena)
CREATE (Huehue)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(hue_miradordieguezolaverri)
CREATE (Huehue)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(hue_unicornioazul)
CREATE (Huehue)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(hue_elmamut)
CREATE (Huehue)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(hue_puedracuache)
CREATE (Huehue)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(hue_cuevaselresumidero)
CREATE (elProgreso)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(pro_sierraMinas)
CREATE (elProgreso)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(pro_aguasTermanes)
CREATE (elProgreso)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(pro_cerroPino)
CREATE (elProgreso)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(pro_parAcuaticoGuastatoya)
CREATE (escuintla)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(esc_pacaya)
CREATE (escuintla)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(esc_ceibaPentandra)
CREATE (escuintla)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(esc_grutasSanPedro)
CREATE (escuintla)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(esc_ElPenion)
CREATE (escuintla)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(esc_playaConacaste)
CREATE (escuintla)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(esc_playaSemillero)
CREATE (escuintla)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(esc_playaRamaBlanca)
CREATE (escuintla)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(esc_playaparedon)
CREATE (escuintla)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(esc_autoSafari)
CREATE (escuintla)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(esc_parqueCalderas)
CREATE (escuintla)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(esc_museoCotzumalguapa)
CREATE (sacatepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sac_volcanAgua)
CREATE (sacatepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sac_iglesiaJocotenango)
CREATE (sacatepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sac_mercadoSanLucas)
CREATE (sacatepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sac_mercadoArtesanias)
CREATE (sacatepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sac_museoArmas)
CREATE (sacatepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sac_museoLibro)
CREATE (sacatepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sac_muesoArteColonial)
CREATE (sacatepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sac_museSantoDomingo)
CREATE (sacatepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sac_museoPalacioArzobispal)
CREATE (sacatepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sac_ruinasDeCompania)
CREATE (sacatepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sac_catedralSanJose)
CREATE (sacatepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sac_conventoSantaClara)
CREATE (sacatepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sac_conventoCapuchinas)
CREATE (sacatepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sac_iglesiaConventoMerced)
CREATE (sacatepequez)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(sac_claustroSanJeronimo)
CREATE (altaVerapaz)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(aver_semucChampey)
CREATE (altaVerapaz)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(aver_lagLachua)
CREATE (altaVerapaz)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(aver_biotopoQuetzal)
CREATE (altaVerapaz)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(aver_grutasLanquin)
CREATE (altaVerapaz)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(aver_hunNalYe)
CREATE (altaVerapaz)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(aver_grutasReyMarcos)
CREATE (altaVerapaz)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(aver_cuevasSetzol)
CREATE (altaVerapaz)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(aver_cuevasBombilPek)
CREATE (altaVerapaz)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(ever_ParqueCentralCoban)
CREATE (altaVerapaz)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(ever_cuevasCandelaria)
CREATE (bajaVerapaz)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(bver_saltoChilasco)
CREATE (bajaVerapaz)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(bver_museoRabinalAchi)
CREATE (bajaVerapaz)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(bver_parroquiaMiguelArcangel)
CREATE (bajaVerapaz)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(bver_museoKomoon)
CREATE (bajaVerapaz)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(bver_cataratasChupadero)
CREATE (bajaVerapaz)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(bver_rioEscondido)
CREATE (bajaVerapaz)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(bver_museoTrapiche)
CREATE (peten)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(pet_lagoItza)
CREATE (cguatemala)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(gt_palacioNacional)
CREATE (cguatemala)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(gt_zooAurora)
CREATE (cguatemala)-[:TURISMO_MUNICIPIO {roles:['Turismo Municipio']}]->(gt_catedralGuatemala)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(peten)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(cguatemala)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(altaVerapaz)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(bajaVerapaz)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(chiquimula)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(elProgreso)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(izabal)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(Zacapa)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(jalapa)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(jutiapa)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(santaRosa)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(chimaltenango)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(escuintla)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(sacatepequez)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(retalhuleu)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(sanMarcos)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(solola)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(suchitepequez)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(totonicapan)
CREATE (espaniol)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(quetzaltenango)
CREATE (pocoman)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(jalapa)
CREATE (chorti)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(chiquimula)
CREATE (chorti)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(Zacapa)
CREATE (garifuna)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(izabal)
CREATE (quekchi)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(izabal)
CREATE (kaqchikel)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(elProgreso)
CREATE (pocoman)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(elProgreso)
CREATE (kaqchikel)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(sacatepequez)
CREATE (achi)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(altaVerapaz)
CREATE (quekchi)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(altaVerapaz)
CREATE (pocomchi)-[:IDIOMA_MUNICIPIO {roles:['Idioma Municipio']}]->(altaVerapaz)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_museoPopolVuh)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pet_tikal)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pet_islaFlores)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pet_resBiosferaMaya)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pet_lagunaYaxha)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pet_pNacLagunaTigre)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pet_pNacSierraLacandon)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pet_lagunaPetexbatun)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pet_petencito)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pet_parqueActunKan)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pet_craterAzul)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_museoArqueologia)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_mapaRelieve)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_mercadoCentral)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_museoFerrocarril)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_museoIxchel)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_museoNacionalArte)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_iglesiaCerritoCarmen)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_hipodromoNorte)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_kaminaljuyu)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_jardinBotanico)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_museoHolocausto)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jut_lagoGuija)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jut_lagunaAtescatempa)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jut_playaMarina)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jut_volcanViboras)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jut_volcanChingo)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jut_volcanIxtepeque)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jut_volcanSuchitan)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jut_volcanMoyuta)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jut_cuevaAndaMira)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jal_cascadaTatasirire)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jal_lagunaAchiotes)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jal_ruinasIngenioAyarza)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jal_iglesiaJilotepeque)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jal_lagunaHoyo)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jal_volcanJumay)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(jal_volcanAlzatete)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(chi_basilicaEsquipulas)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(chi_cuevaMinas)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(chi_fincaGirasoles)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(chi_volcanIpala)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(chi_parqueMontecristo)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(zac_cerroMiramundos)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(zac_museoFerrocarril)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(zac_ValleDorado)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(zac_museoPalenGeolo)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(iz_arqueoQuirigua)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(iz_castilloSanFelipe)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(iz_lagoIzabal)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(iz_playaDorada)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(iz_rioDulce)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(iz_bahiaAmatique)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(iz_puntaPalma)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(iz_playaGraciosa)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(iz_biotopoChacon)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(iz_cayosDiablo)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_lagunaayarza)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_laslisas)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_lagunaixpaco)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_monterrico)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_canaldechiquimulilla)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_cascadasdelosamates)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_hawaii)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_lagunaelpino)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_volcantecuamburro)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_cascadalaconcepcion)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_volcancruzquemada)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_riolosesclavos)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(chi_iximche)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(chi_lagunachicoy)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(chi_casaxaraymolino)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(chi_volcandefuego)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(chi_galeriadeartetzutujil)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(chi_mixcoviejo)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(chi_volcandeacatenango)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(chi_fincacalerachichavac)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(chi_patzun)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(ret_takalikabaj)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(ret_museoxulik)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(ret_reservapatrocinio)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(ret_xocomil)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(ret_champerico)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(ret_takalikmayalodge)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(ret_xetulul)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_cataratalaigualdad)
CREATE (lluvioso)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_parqueregionalmunicipalastillero)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_refugiodelquetzal)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_volcantajumulco)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_montainbike)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_tilapa)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(san_volcantacana)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_miradorixchel)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_santacruzlalaguna)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_sanjuanlalaguna)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(so_theyogaforest)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_cafeloco)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_miradorrostromaya)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_sanperdrolalaguna)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_museolacustre)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_clubvenaca)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_sanantoniopalopo)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_lacasadedonmemo)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_santiagoatitlan)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_reservanaturalatitlan)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_yatchclubatitlan)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_sanmarcoslalaguna)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_santacatarinapalopo)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_cerrotzankujil)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_sanlucastoliman)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_miradordeatitlan)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_catarataensolola)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_volcansanpedro)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sol_nahuala)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(suc_cafechocola)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(suc_elchorrosdelcarme)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(suc_relojcentenariochocola)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(suc_cerrocabezadeburro)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(suc_chiquistepeque)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(suc_fincalasnubes)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(tot_elaprisco)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(tot_riscosdemomostenango)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(tot_miradorcerropaclom)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(tot_igleasiasanandresxecul)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(tot_mercadosanfranciscoelalto)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(tot_cascadapatrubala)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(tot_parqueecologicochajilsiwan)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(tot_volcancuxliquel)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(tot_sancristobal)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(tot_momostenango)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(tot_sanfranciscoelalto)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(tot_cuevasdesanmiguel)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(tot_aguastermalessanbartolo)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(tot_nueveriscos)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(que_fuentesgeorginas)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(que_ermitadelaconcepcionsalcaja)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(que_elviejopalmar)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(que_museodelferrocarrildelosaltos)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(QUE_LAGUNAYVOLCANDECHICABAL)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(que_cerroelbaul)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(que_templominerva)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(que_casadelaculturanoj)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(que_volcansantamaria)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(que_museodelahistorianatural)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(que_pasajeenriquez)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(que_lascumbresecosaunas)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(que_museoixkikdeltrajemaya)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(que_teatromunicipal)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(que_volcansantiaguito)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(que_volcancerroquemado)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(que_iglesiasannicolas)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(que_volcanzunil)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(hue_cenotesdecandelaria)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(hue_lagunamaxbal)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(hue_rioazul)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(hue_lagunabrava)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(hue_ruinasdezaculeu)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(hue_elcimarron)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(hue_senderoecologicolameceta)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(hue_rioquisil)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(hue_fincachacula)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(hue_lagunamagdalena)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(hue_miradordieguezolaverri)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(hue_unicornioazul)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(hue_elmamut)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(hue_puedracuache)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(hue_cuevaselresumidero)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pro_sierraMinas)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pro_aguasTermanes)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pro_cerroPino)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pro_parAcuaticoGuastatoya)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(esc_pacaya)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(esc_ceibaPentandra)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(esc_grutasSanPedro)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(esc_ElPenion)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(esc_playaConacaste)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(esc_playaSemillero)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(esc_playaRamaBlanca)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(esc_playaparedon)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(esc_autoSafari)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(esc_parqueCalderas)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(esc_museoCotzumalguapa)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sac_volcanAgua)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sac_iglesiaJocotenango)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sac_mercadoSanLucas)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sac_mercadoArtesanias)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sac_museoArmas)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sac_museoLibro)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sac_muesoArteColonial)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sac_museSantoDomingo)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sac_museoPalacioArzobispal)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sac_ruinasDeCompania)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sac_catedralSanJose)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sac_conventoSantaClara)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sac_conventoCapuchinas)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sac_iglesiaConventoMerced)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(sac_claustroSanJeronimo)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(aver_semucChampey)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(aver_lagLachua)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(aver_biotopoQuetzal)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(aver_grutasLanquin)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(aver_hunNalYe)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(aver_grutasReyMarcos)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(aver_cuevasSetzol)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(aver_cuevasBombilPek)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(ever_ParqueCentralCoban)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(ever_cuevasCandelaria)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(bver_saltoChilasco)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(bver_museoRabinalAchi)
CREATE (frio)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(bver_parroquiaMiguelArcangel)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(bver_museoKomoon)
CREATE (humedo)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(bver_cataratasChupadero)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(bver_rioEscondido)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(bver_museoTrapiche)
CREATE (calido)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(pet_lagoItza)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_palacioNacional)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_zooAurora)
CREATE (templado)-[:TIENE_CLIMA {roles:['Clima Lugar']}]->(gt_catedralGuatemala)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pet_lagoItza)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_palacioNacional)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_zooAurora)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_catedralGuatemala)
CREATE (religioso)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_catedralGuatemala)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_museoPopolVuh)
CREATE (arqueologico)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pet_tikal)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pet_tikal)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pet_islaFlores)
CREATE (gastronomico)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pet_islaFlores)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pet_resBiosferaMaya)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pet_resBiosferaMaya)
CREATE (arqueologico)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pet_resBiosferaMaya)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pet_lagunaYaxha)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pet_pNacLagunaTigre)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pet_pNacSierraLacandon)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pet_lagunaPetexbatun)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pet_petencito)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pet_petencito)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pet_parqueActunKan)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pet_parqueActunKan)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pet_craterAzul)
CREATE (etnoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_museoArqueologia)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_museoArqueologia)
CREATE (arqueologico)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_museoArqueologia)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_mapaRelieve)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_mercadoCentral)
CREATE (gastronomico)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_mercadoCentral)
CREATE (etnoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_museoIxchel)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_museoIxchel)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_museoFerrocarril)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_museoNacionalArte)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_iglesiaCerritoCarmen)
CREATE (religioso)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_iglesiaCerritoCarmen)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_hipodromoNorte)
CREATE (deportivo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_hipodromoNorte)
CREATE (arqueologico)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_kaminaljuyu)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_kaminaljuyu)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_jardinBotanico)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_jardinBotanico)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_museoHolocausto)
CREATE (etnoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(gt_museoHolocausto)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jut_lagoGuija)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jut_lagunaAtescatempa)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jut_playaMarina)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jut_volcanViboras)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jut_volcanViboras)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jut_volcanChingo)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jut_volcanChingo)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jut_volcanIxtepeque)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jut_volcanIxtepeque)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jut_volcanSuchitan)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jut_volcanSuchitan)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jut_volcanMoyuta)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jut_volcanMoyuta)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jut_cuevaAndaMira)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jut_cuevaAndaMira)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jal_cascadaTatasirire)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jal_cascadaTatasirire)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jal_lagunaAchiotes)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jal_ruinasIngenioAyarza)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jal_iglesiaJilotepeque)
CREATE (religioso)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jal_iglesiaJilotepeque)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jal_lagunaHoyo)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jal_volcanJumay)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jal_volcanJumay)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jal_volcanAlzatete)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jal_volcanAlzatete)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(chi_basilicaEsquipulas)
CREATE (religioso)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(chi_basilicaEsquipulas)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(chi_cuevaMinas)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(chi_fincaGirasoles)
CREATE (etnoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(chi_cuevaMinas)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(chi_volcanIpala)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(chi_volcanIpala)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(chi_parqueMontecristo)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(chi_parqueMontecristo)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(zac_cerroMiramundos)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(zac_museoFerrocarril)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(zac_ValleDorado)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(zac_museoPalenGeolo)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(zac_museoPalenGeolo)
CREATE (arqueologico)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(iz_arqueoQuirigua)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(iz_castilloSanFelipe)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(iz_lagoIzabal)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(iz_lagoIzabal)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jut_lagunaAtescatempa)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jal_lagunaHoyo)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(jal_lagunaAchiotes)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(iz_playaDorada)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(iz_playaDorada)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(iz_rioDulce)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(iz_rioDulce)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(iz_bahiaAmatique)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(iz_puntaPalma)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(iz_puntaPalma)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(iz_playaGraciosa)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(iz_playaGraciosa)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(iz_biotopoChacon)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(iz_biotopoChacon)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(iz_cayosDiablo)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(iz_cayosDiablo)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pro_sierraMinas)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pro_sierraMinas)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pro_aguasTermanes)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pro_aguasTermanes)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pro_cerroPino)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(pro_parAcuaticoGuastatoya)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(esc_pacaya)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(esc_pacaya)
CREATE (arqueologico)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(esc_ceibaPentandra)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(esc_ceibaPentandra)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(esc_grutasSanPedro)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(esc_grutasSanPedro)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(esc_ElPenion)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(esc_ElPenion)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(esc_playaConacaste)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(esc_playaSemillero)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(esc_playaRamaBlanca)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(esc_playaparedon)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(esc_autoSafari)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(esc_parqueCalderas)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(esc_parqueCalderas)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(esc_museoCotzumalguapa)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(sac_volcanAgua)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(sac_volcanAgua)
CREATE (religioso)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(sac_iglesiaJocotenango)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(sac_iglesiaJocotenango)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(sac_mercadoSanLucas)
CREATE (gastronomico)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(sac_mercadoSanLucas)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(sac_mercadoArtesanias)
CREATE (etnoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(sac_mercadoArtesanias)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(sac_museoArmas)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(sac_museoLibro)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(sac_muesoArteColonial)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(sac_museSantoDomingo)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(sac_museoPalacioArzobispal)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(sac_ruinasDeCompania)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(sac_catedralSanJose)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(sac_conventoSantaClara)
CREATE (religioso)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(sac_conventoSantaClara)
CREATE (religioso)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(sac_catedralSanJose)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(sac_conventoCapuchinas)
CREATE (religioso)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(sac_conventoCapuchinas)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(sac_iglesiaConventoMerced)
CREATE (religioso)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(sac_iglesiaConventoMerced)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(sac_claustroSanJeronimo)
CREATE (religioso)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(sac_claustroSanJeronimo)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aver_semucChampey)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aver_semucChampey)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aver_lagLachua)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aver_lagLachua)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aver_biotopoQuetzal)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aver_biotopoQuetzal)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aver_grutasLanquin)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aver_grutasLanquin)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aver_hunNalYe)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aver_hunNalYe)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aver_grutasReyMarcos)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aver_grutasReyMarcos)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aver_cuevasSetzol)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aver_cuevasSetzol)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aver_cuevasBombilPek)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(aver_cuevasBombilPek)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ever_ParqueCentralCoban)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ever_cuevasCandelaria)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(ever_cuevasCandelaria)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(bver_museoRabinalAchi)
CREATE (religioso)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(bver_parroquiaMiguelArcangel)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(bver_parroquiaMiguelArcangel)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(bver_museoKomoon)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(bver_cataratasChupadero)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(bver_cataratasChupadero)
CREATE (aventura)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(bver_rioEscondido)
CREATE (ecoturismo)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(bver_rioEscondido)
CREATE (cultural)-[:CATEGORIA_TURISMO {roles:['Categoria Turismo']}]->(bver_museoTrapiche)
